06/Jan/2024 17:48:08   INFO  /home/alprostov/PycharmProjects/sakhlis/sakhlis/web/app_site/views.py changed, reloading.  None
INFO:django.utils.autoreload:/home/alprostov/PycharmProjects/sakhlis/sakhlis/web/app_site/views.py changed, reloading.
06/Jan/2024 17:48:10   INFO  Watching for file changes with StatReloader  None
06/Jan/2024 17:48:12   INFO  "GET /ordersearch/ HTTP/1.1" 200 55627  None
INFO:django.server:"GET /ordersearch/ HTTP/1.1" 200 55627
06/Jan/2024 17:48:12   WARNING  "GET /static/js/counter.js HTTP/1.1" 404 1798  None
WARNING:django.server:"GET /static/js/counter.js HTTP/1.1" 404 1798
06/Jan/2024 17:48:29   INFO  /home/alprostov/PycharmProjects/sakhlis/sakhlis/web/app_site/views.py changed, reloading.  None
INFO:django.utils.autoreload:/home/alprostov/PycharmProjects/sakhlis/sakhlis/web/app_site/views.py changed, reloading.
06/Jan/2024 17:48:31   INFO  Watching for file changes with StatReloader  None
06/Jan/2024 17:48:33   ERROR  Internal Server Error: /ordersearch/  (<class 'TypeError'>, TypeError("int() argument must be a string, a bytes-like object or a real number, not 'NoneType'"), <traceback object at 0x7fc4bc3b5f80>)
Traceback (most recent call last):
  File "/home/alprostov/PycharmProjects/sakhlis/venv3/lib/python3.11/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/home/alprostov/PycharmProjects/sakhlis/venv3/lib/python3.11/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/alprostov/PycharmProjects/sakhlis/venv3/lib/python3.11/site-packages/django/views/generic/base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/alprostov/PycharmProjects/sakhlis/venv3/lib/python3.11/site-packages/django/contrib/auth/mixins.py", line 73, in dispatch
    return super().dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/alprostov/PycharmProjects/sakhlis/venv3/lib/python3.11/site-packages/django/views/generic/base.py", line 143, in dispatch
    return handler(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/alprostov/PycharmProjects/sakhlis/venv3/lib/python3.11/site-packages/django/views/generic/list.py", line 174, in get
    context = self.get_context_data()
              ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/alprostov/PycharmProjects/sakhlis/sakhlis/web/app_site/views.py", line 278, in get_context_data
    print(type(int(c.get('Summ'))))
               ^^^^^^^^^^^^^^^^^^
TypeError: int() argument must be a string, a bytes-like object or a real number, not 'NoneType'
ERROR:django.request:Internal Server Error: /ordersearch/
Traceback (most recent call last):
  File "/home/alprostov/PycharmProjects/sakhlis/venv3/lib/python3.11/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/home/alprostov/PycharmProjects/sakhlis/venv3/lib/python3.11/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/alprostov/PycharmProjects/sakhlis/venv3/lib/python3.11/site-packages/django/views/generic/base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/alprostov/PycharmProjects/sakhlis/venv3/lib/python3.11/site-packages/django/contrib/auth/mixins.py", line 73, in dispatch
    return super().dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/alprostov/PycharmProjects/sakhlis/venv3/lib/python3.11/site-packages/django/views/generic/base.py", line 143, in dispatch
    return handler(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/alprostov/PycharmProjects/sakhlis/venv3/lib/python3.11/site-packages/django/views/generic/list.py", line 174, in get
    context = self.get_context_data()
              ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/alprostov/PycharmProjects/sakhlis/sakhlis/web/app_site/views.py", line 278, in get_context_data
    print(type(int(c.get('Summ'))))
               ^^^^^^^^^^^^^^^^^^
TypeError: int() argument must be a string, a bytes-like object or a real number, not 'NoneType'
06/Jan/2024 17:48:33   ERROR  "GET /ordersearch/ HTTP/1.1" 500 100942  None
ERROR:django.server:"GET /ordersearch/ HTTP/1.1" 500 100942
06/Jan/2024 17:48:58   INFO  /home/alprostov/PycharmProjects/sakhlis/sakhlis/web/app_site/views.py changed, reloading.  None
INFO:django.utils.autoreload:/home/alprostov/PycharmProjects/sakhlis/sakhlis/web/app_site/views.py changed, reloading.
06/Jan/2024 17:49:00   INFO  Watching for file changes with StatReloader  None
06/Jan/2024 17:49:00   ERROR  Internal Server Error: /ordersearch/  (<class 'ValueError'>, ValueError("invalid literal for int() with base 10: 'None'"), <traceback object at 0x7fe37c1d5480>)
Traceback (most recent call last):
  File "/home/alprostov/PycharmProjects/sakhlis/venv3/lib/python3.11/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/home/alprostov/PycharmProjects/sakhlis/venv3/lib/python3.11/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/alprostov/PycharmProjects/sakhlis/venv3/lib/python3.11/site-packages/django/views/generic/base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/alprostov/PycharmProjects/sakhlis/venv3/lib/python3.11/site-packages/django/contrib/auth/mixins.py", line 73, in dispatch
    return super().dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/alprostov/PycharmProjects/sakhlis/venv3/lib/python3.11/site-packages/django/views/generic/base.py", line 143, in dispatch
    return handler(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/alprostov/PycharmProjects/sakhlis/venv3/lib/python3.11/site-packages/django/views/generic/list.py", line 174, in get
    context = self.get_context_data()
              ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/alprostov/PycharmProjects/sakhlis/sakhlis/web/app_site/views.py", line 278, in get_context_data
    print(type(int(str(c.get('Summ')))))
               ^^^^^^^^^^^^^^^^^^^^^^^
ValueError: invalid literal for int() with base 10: 'None'
ERROR:django.request:Internal Server Error: /ordersearch/
Traceback (most recent call last):
  File "/home/alprostov/PycharmProjects/sakhlis/venv3/lib/python3.11/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/home/alprostov/PycharmProjects/sakhlis/venv3/lib/python3.11/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/alprostov/PycharmProjects/sakhlis/venv3/lib/python3.11/site-packages/django/views/generic/base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/alprostov/PycharmProjects/sakhlis/venv3/lib/python3.11/site-packages/django/contrib/auth/mixins.py", line 73, in dispatch
    return super().dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/alprostov/PycharmProjects/sakhlis/venv3/lib/python3.11/site-packages/django/views/generic/base.py", line 143, in dispatch
    return handler(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/alprostov/PycharmProjects/sakhlis/venv3/lib/python3.11/site-packages/django/views/generic/list.py", line 174, in get
    context = self.get_context_data()
              ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/alprostov/PycharmProjects/sakhlis/sakhlis/web/app_site/views.py", line 278, in get_context_data
    print(type(int(str(c.get('Summ')))))
               ^^^^^^^^^^^^^^^^^^^^^^^
ValueError: invalid literal for int() with base 10: 'None'
06/Jan/2024 17:49:01   ERROR  "GET /ordersearch/ HTTP/1.1" 500 100812  None
ERROR:django.server:"GET /ordersearch/ HTTP/1.1" 500 100812
06/Jan/2024 17:49:14   INFO  /home/alprostov/PycharmProjects/sakhlis/sakhlis/web/app_site/views.py changed, reloading.  None
INFO:django.utils.autoreload:/home/alprostov/PycharmProjects/sakhlis/sakhlis/web/app_site/views.py changed, reloading.
06/Jan/2024 17:49:16   INFO  Watching for file changes with StatReloader  None
06/Jan/2024 17:49:18   INFO  "GET /ordersearch/ HTTP/1.1" 200 55628  None
INFO:django.server:"GET /ordersearch/ HTTP/1.1" 200 55628
06/Jan/2024 17:49:18   WARNING  "GET /static/js/counter.js HTTP/1.1" 404 1798  None
WARNING:django.server:"GET /static/js/counter.js HTTP/1.1" 404 1798
06/Jan/2024 17:49:45   INFO  /home/alprostov/PycharmProjects/sakhlis/sakhlis/web/app_site/views.py changed, reloading.  None
INFO:django.utils.autoreload:/home/alprostov/PycharmProjects/sakhlis/sakhlis/web/app_site/views.py changed, reloading.
06/Jan/2024 17:49:47   INFO  Watching for file changes with StatReloader  None
06/Jan/2024 17:49:47   ERROR  Internal Server Error: /ordersearch/  (<class 'TypeError'>, TypeError("unsupported operand type(s) for +: 'int' and 'NoneType'"), <traceback object at 0x7f62755c9440>)
Traceback (most recent call last):
  File "/home/alprostov/PycharmProjects/sakhlis/venv3/lib/python3.11/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/home/alprostov/PycharmProjects/sakhlis/venv3/lib/python3.11/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/alprostov/PycharmProjects/sakhlis/venv3/lib/python3.11/site-packages/django/views/generic/base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/alprostov/PycharmProjects/sakhlis/venv3/lib/python3.11/site-packages/django/contrib/auth/mixins.py", line 73, in dispatch
    return super().dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/alprostov/PycharmProjects/sakhlis/venv3/lib/python3.11/site-packages/django/views/generic/base.py", line 143, in dispatch
    return handler(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/alprostov/PycharmProjects/sakhlis/venv3/lib/python3.11/site-packages/django/views/generic/list.py", line 174, in get
    context = self.get_context_data()
              ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/alprostov/PycharmProjects/sakhlis/sakhlis/web/app_site/views.py", line 279, in get_context_data
    rrr=rrr+c.get('Summ')
        ~~~^~~~~~~~~~~~~~
TypeError: unsupported operand type(s) for +: 'int' and 'NoneType'
ERROR:django.request:Internal Server Error: /ordersearch/
Traceback (most recent call last):
  File "/home/alprostov/PycharmProjects/sakhlis/venv3/lib/python3.11/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/home/alprostov/PycharmProjects/sakhlis/venv3/lib/python3.11/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/alprostov/PycharmProjects/sakhlis/venv3/lib/python3.11/site-packages/django/views/generic/base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/alprostov/PycharmProjects/sakhlis/venv3/lib/python3.11/site-packages/django/contrib/auth/mixins.py", line 73, in dispatch
    return super().dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/alprostov/PycharmProjects/sakhlis/venv3/lib/python3.11/site-packages/django/views/generic/base.py", line 143, in dispatch
    return handler(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/alprostov/PycharmProjects/sakhlis/venv3/lib/python3.11/site-packages/django/views/generic/list.py", line 174, in get
    context = self.get_context_data()
              ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/alprostov/PycharmProjects/sakhlis/sakhlis/web/app_site/views.py", line 279, in get_context_data
    rrr=rrr+c.get('Summ')
        ~~~^~~~~~~~~~~~~~
TypeError: unsupported operand type(s) for +: 'int' and 'NoneType'
06/Jan/2024 17:49:47   ERROR  "GET /ordersearch/ HTTP/1.1" 500 100817  None
ERROR:django.server:"GET /ordersearch/ HTTP/1.1" 500 100817
06/Jan/2024 17:50:03   INFO  /home/alprostov/PycharmProjects/sakhlis/sakhlis/web/app_site/views.py changed, reloading.  None
INFO:django.utils.autoreload:/home/alprostov/PycharmProjects/sakhlis/sakhlis/web/app_site/views.py changed, reloading.
06/Jan/2024 17:50:05   INFO  Watching for file changes with StatReloader  None
06/Jan/2024 17:50:06   ERROR  Internal Server Error: /ordersearch/  (<class 'TypeError'>, TypeError("unsupported operand type(s) for +: 'int' and 'NoneType'"), <traceback object at 0x7f49053f1200>)
Traceback (most recent call last):
  File "/home/alprostov/PycharmProjects/sakhlis/venv3/lib/python3.11/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/home/alprostov/PycharmProjects/sakhlis/venv3/lib/python3.11/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/alprostov/PycharmProjects/sakhlis/venv3/lib/python3.11/site-packages/django/views/generic/base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/alprostov/PycharmProjects/sakhlis/venv3/lib/python3.11/site-packages/django/contrib/auth/mixins.py", line 73, in dispatch
    return super().dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/alprostov/PycharmProjects/sakhlis/venv3/lib/python3.11/site-packages/django/views/generic/base.py", line 143, in dispatch
    return handler(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/alprostov/PycharmProjects/sakhlis/venv3/lib/python3.11/site-packages/django/views/generic/list.py", line 174, in get
    context = self.get_context_data()
              ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/alprostov/PycharmProjects/sakhlis/sakhlis/web/app_site/views.py", line 279, in get_context_data
    rrr=rrr+c.get('Summ')
        ~~~^~~~~~~~~~~~~~
TypeError: unsupported operand type(s) for +: 'int' and 'NoneType'
ERROR:django.request:Internal Server Error: /ordersearch/
Traceback (most recent call last):
  File "/home/alprostov/PycharmProjects/sakhlis/venv3/lib/python3.11/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/home/alprostov/PycharmProjects/sakhlis/venv3/lib/python3.11/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/alprostov/PycharmProjects/sakhlis/venv3/lib/python3.11/site-packages/django/views/generic/base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/alprostov/PycharmProjects/sakhlis/venv3/lib/python3.11/site-packages/django/contrib/auth/mixins.py", line 73, in dispatch
    return super().dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/alprostov/PycharmProjects/sakhlis/venv3/lib/python3.11/site-packages/django/views/generic/base.py", line 143, in dispatch
    return handler(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/alprostov/PycharmProjects/sakhlis/venv3/lib/python3.11/site-packages/django/views/generic/list.py", line 174, in get
    context = self.get_context_data()
              ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/alprostov/PycharmProjects/sakhlis/sakhlis/web/app_site/views.py", line 279, in get_context_data
    rrr=rrr+c.get('Summ')
        ~~~^~~~~~~~~~~~~~
TypeError: unsupported operand type(s) for +: 'int' and 'NoneType'
06/Jan/2024 17:50:06   ERROR  "GET /ordersearch/ HTTP/1.1" 500 100817  None
ERROR:django.server:"GET /ordersearch/ HTTP/1.1" 500 100817
06/Jan/2024 17:59:21   INFO  Watching for file changes with StatReloader  None
06/Jan/2024 17:59:38   INFO  Watching for file changes with StatReloader  None
06/Jan/2024 18:00:47   ERROR  Internal Server Error: /ordersearch/  (<class 'TypeError'>, TypeError("unsupported operand type(s) for +: 'int' and 'NoneType'"), <traceback object at 0x7f7f40746080>)
Traceback (most recent call last):
  File "/home/alprostov/PycharmProjects/sakhlis/venv3/lib/python3.11/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/home/alprostov/PycharmProjects/sakhlis/venv3/lib/python3.11/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/alprostov/PycharmProjects/sakhlis/venv3/lib/python3.11/site-packages/django/views/generic/base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/alprostov/PycharmProjects/sakhlis/venv3/lib/python3.11/site-packages/django/contrib/auth/mixins.py", line 73, in dispatch
    return super().dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/alprostov/PycharmProjects/sakhlis/venv3/lib/python3.11/site-packages/django/views/generic/base.py", line 143, in dispatch
    return handler(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/alprostov/PycharmProjects/sakhlis/venv3/lib/python3.11/site-packages/django/views/generic/list.py", line 174, in get
    context = self.get_context_data()
              ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/alprostov/PycharmProjects/sakhlis/sakhlis/web/app_site/views.py", line 279, in get_context_data
    rrr=rrr+c.get('Summ')
        ~~~^~~~~~~~~~~~~~
TypeError: unsupported operand type(s) for +: 'int' and 'NoneType'
ERROR:django.request:Internal Server Error: /ordersearch/
Traceback (most recent call last):
  File "/home/alprostov/PycharmProjects/sakhlis/venv3/lib/python3.11/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/home/alprostov/PycharmProjects/sakhlis/venv3/lib/python3.11/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/alprostov/PycharmProjects/sakhlis/venv3/lib/python3.11/site-packages/django/views/generic/base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/alprostov/PycharmProjects/sakhlis/venv3/lib/python3.11/site-packages/django/contrib/auth/mixins.py", line 73, in dispatch
    return super().dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/alprostov/PycharmProjects/sakhlis/venv3/lib/python3.11/site-packages/django/views/generic/base.py", line 143, in dispatch
    return handler(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/alprostov/PycharmProjects/sakhlis/venv3/lib/python3.11/site-packages/django/views/generic/list.py", line 174, in get
    context = self.get_context_data()
              ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/alprostov/PycharmProjects/sakhlis/sakhlis/web/app_site/views.py", line 279, in get_context_data
    rrr=rrr+c.get('Summ')
        ~~~^~~~~~~~~~~~~~
TypeError: unsupported operand type(s) for +: 'int' and 'NoneType'
06/Jan/2024 18:00:47   ERROR  "GET /ordersearch/ HTTP/1.1" 500 112711  None
ERROR:django.server:"GET /ordersearch/ HTTP/1.1" 500 112711
06/Jan/2024 18:01:42   INFO  Watching for file changes with StatReloader  None
06/Jan/2024 18:01:48   INFO  "GET /ordersearch/ HTTP/1.1" 200 55628  None
INFO:django.server:"GET /ordersearch/ HTTP/1.1" 200 55628
06/Jan/2024 18:01:48   WARNING  "GET /static/js/counter.js HTTP/1.1" 404 1798  None
WARNING:django.server:"GET /static/js/counter.js HTTP/1.1" 404 1798
06/Jan/2024 18:01:51   INFO  "GET /ordersearch/ HTTP/1.1" 200 55626  None
INFO:django.server:"GET /ordersearch/ HTTP/1.1" 200 55626
06/Jan/2024 18:01:51   WARNING  "GET /static/js/counter.js HTTP/1.1" 404 1798  None
WARNING:django.server:"GET /static/js/counter.js HTTP/1.1" 404 1798
06/Jan/2024 18:02:05   INFO  /home/alprostov/PycharmProjects/sakhlis/sakhlis/web/app_site/views.py changed, reloading.  None
INFO:django.utils.autoreload:/home/alprostov/PycharmProjects/sakhlis/sakhlis/web/app_site/views.py changed, reloading.
06/Jan/2024 18:02:07   INFO  Watching for file changes with StatReloader  None
06/Jan/2024 18:02:10   INFO  "GET /ordersearch/ HTTP/1.1" 200 55628  None
INFO:django.server:"GET /ordersearch/ HTTP/1.1" 200 55628
06/Jan/2024 18:02:10   WARNING  "GET /static/js/counter.js HTTP/1.1" 404 1798  None
WARNING:django.server:"GET /static/js/counter.js HTTP/1.1" 404 1798
06/Jan/2024 18:02:29   INFO  "GET /ordersearch/ HTTP/1.1" 200 55631  None
INFO:django.server:"GET /ordersearch/ HTTP/1.1" 200 55631
06/Jan/2024 18:02:29   WARNING  "GET /static/js/counter.js HTTP/1.1" 404 1798  None
WARNING:django.server:"GET /static/js/counter.js HTTP/1.1" 404 1798
06/Jan/2024 18:02:36   INFO  "GET /user/51 HTTP/1.1" 200 16064  None
INFO:django.server:"GET /user/51 HTTP/1.1" 200 16064
06/Jan/2024 18:02:36   WARNING  "GET /static/js/counter.js HTTP/1.1" 404 1798  None
WARNING:django.server:"GET /static/js/counter.js HTTP/1.1" 404 1798
06/Jan/2024 18:02:41   INFO  "GET /list_order?work_status=END HTTP/1.1" 200 53766  None
INFO:django.server:"GET /list_order?work_status=END HTTP/1.1" 200 53766
06/Jan/2024 18:02:41   WARNING  "GET /static/js/counter.js HTTP/1.1" 404 1798  None
WARNING:django.server:"GET /static/js/counter.js HTTP/1.1" 404 1798
06/Jan/2024 18:02:44   INFO  "GET /ordersearch/ HTTP/1.1" 200 55631  None
INFO:django.server:"GET /ordersearch/ HTTP/1.1" 200 55631
06/Jan/2024 18:02:44   WARNING  "GET /static/js/counter.js HTTP/1.1" 404 1798  None
WARNING:django.server:"GET /static/js/counter.js HTTP/1.1" 404 1798
06/Jan/2024 18:02:52   INFO  /home/alprostov/PycharmProjects/sakhlis/sakhlis/web/app_site/views.py changed, reloading.  None
INFO:django.utils.autoreload:/home/alprostov/PycharmProjects/sakhlis/sakhlis/web/app_site/views.py changed, reloading.
06/Jan/2024 18:02:54   INFO  Watching for file changes with StatReloader  None
06/Jan/2024 18:02:57   INFO  "GET /ordersearch/ HTTP/1.1" 200 55633  None
INFO:django.server:"GET /ordersearch/ HTTP/1.1" 200 55633
06/Jan/2024 18:02:57   WARNING  "GET /static/js/counter.js HTTP/1.1" 404 1798  None
WARNING:django.server:"GET /static/js/counter.js HTTP/1.1" 404 1798
06/Jan/2024 18:03:08   INFO  "GET /user/51 HTTP/1.1" 200 16064  None
INFO:django.server:"GET /user/51 HTTP/1.1" 200 16064
06/Jan/2024 18:03:08   WARNING  "GET /static/js/counter.js HTTP/1.1" 404 1798  None
WARNING:django.server:"GET /static/js/counter.js HTTP/1.1" 404 1798
06/Jan/2024 18:03:25   INFO  "GET /ordersearch/?time_in_sence=&time_in_until=&order_status=RCV&repairer_id=51&customer_name=&customer_phone=&customer_telegram=&address_city=&adress_street_app=&address_num= HTTP/1.1" 200 30006  None
INFO:django.server:"GET /ordersearch/?time_in_sence=&time_in_until=&order_status=RCV&repairer_id=51&customer_name=&customer_phone=&customer_telegram=&address_city=&adress_street_app=&address_num= HTTP/1.1" 200 30006
06/Jan/2024 18:03:25   WARNING  "GET /static/js/counter.js HTTP/1.1" 404 1798  None
WARNING:django.server:"GET /static/js/counter.js HTTP/1.1" 404 1798
06/Jan/2024 18:03:36   INFO  "GET /ordersearch/?time_in_sence=&time_in_until=&order_status=END&repairer_id=51&customer_name=&customer_phone=&customer_telegram=&address_city=&adress_street_app=&address_num= HTTP/1.1" 200 56113  None
INFO:django.server:"GET /ordersearch/?time_in_sence=&time_in_until=&order_status=END&repairer_id=51&customer_name=&customer_phone=&customer_telegram=&address_city=&adress_street_app=&address_num= HTTP/1.1" 200 56113
06/Jan/2024 18:03:36   WARNING  "GET /static/js/counter.js HTTP/1.1" 404 1798  None
WARNING:django.server:"GET /static/js/counter.js HTTP/1.1" 404 1798
06/Jan/2024 18:04:25   INFO  "GET /ordersearch/?time_in_sence=2024-01-01&time_in_until=2024-01-06&order_status=END&repairer_id=51&customer_name=&customer_phone=&customer_telegram=&address_city=&adress_street_app=&address_num= HTTP/1.1" 200 34679  None
INFO:django.server:"GET /ordersearch/?time_in_sence=2024-01-01&time_in_until=2024-01-06&order_status=END&repairer_id=51&customer_name=&customer_phone=&customer_telegram=&address_city=&adress_street_app=&address_num= HTTP/1.1" 200 34679
06/Jan/2024 18:04:25   WARNING  "GET /static/js/counter.js HTTP/1.1" 404 1798  None
WARNING:django.server:"GET /static/js/counter.js HTTP/1.1" 404 1798
06/Jan/2024 18:04:29   INFO  "GET /ordersearch/?time_in_sence=2024-01-01&time_in_until=2024-01-06&order_status=SND&repairer_id=51&customer_name=&customer_phone=&customer_telegram=&address_city=&adress_street_app=&address_num= HTTP/1.1" 200 20497  None
INFO:django.server:"GET /ordersearch/?time_in_sence=2024-01-01&time_in_until=2024-01-06&order_status=SND&repairer_id=51&customer_name=&customer_phone=&customer_telegram=&address_city=&adress_street_app=&address_num= HTTP/1.1" 200 20497
06/Jan/2024 18:04:29   WARNING  "GET /static/js/counter.js HTTP/1.1" 404 1798  None
WARNING:django.server:"GET /static/js/counter.js HTTP/1.1" 404 1798
06/Jan/2024 18:04:31   INFO  "GET /ordersearch/?time_in_sence=2024-01-01&time_in_until=2024-01-06&order_status=BEG&repairer_id=51&customer_name=&customer_phone=&customer_telegram=&address_city=&adress_street_app=&address_num= HTTP/1.1" 200 20497  None
INFO:django.server:"GET /ordersearch/?time_in_sence=2024-01-01&time_in_until=2024-01-06&order_status=BEG&repairer_id=51&customer_name=&customer_phone=&customer_telegram=&address_city=&adress_street_app=&address_num= HTTP/1.1" 200 20497
06/Jan/2024 18:04:31   WARNING  "GET /static/js/counter.js HTTP/1.1" 404 1798  None
WARNING:django.server:"GET /static/js/counter.js HTTP/1.1" 404 1798
06/Jan/2024 18:04:34   INFO  "GET /ordersearch/?time_in_sence=2024-01-01&time_in_until=2024-01-06&order_status=END&repairer_id=51&customer_name=&customer_phone=&customer_telegram=&address_city=&adress_street_app=&address_num= HTTP/1.1" 200 34677  None
INFO:django.server:"GET /ordersearch/?time_in_sence=2024-01-01&time_in_until=2024-01-06&order_status=END&repairer_id=51&customer_name=&customer_phone=&customer_telegram=&address_city=&adress_street_app=&address_num= HTTP/1.1" 200 34677
06/Jan/2024 18:04:34   WARNING  "GET /static/js/counter.js HTTP/1.1" 404 1798  None
WARNING:django.server:"GET /static/js/counter.js HTTP/1.1" 404 1798
06/Jan/2024 18:04:45   INFO  "GET /ordersearch/?time_in_sence=2024-01-05&time_in_until=2024-01-06&order_status=END&repairer_id=51&customer_name=&customer_phone=&customer_telegram=&address_city=&adress_street_app=&address_num= HTTP/1.1" 200 20497  None
INFO:django.server:"GET /ordersearch/?time_in_sence=2024-01-05&time_in_until=2024-01-06&order_status=END&repairer_id=51&customer_name=&customer_phone=&customer_telegram=&address_city=&adress_street_app=&address_num= HTTP/1.1" 200 20497
06/Jan/2024 18:04:45   WARNING  "GET /static/js/counter.js HTTP/1.1" 404 1798  None
WARNING:django.server:"GET /static/js/counter.js HTTP/1.1" 404 1798
06/Jan/2024 18:04:48   INFO  "GET /ordersearch/?time_in_sence=2024-01-04&time_in_until=2024-01-06&order_status=END&repairer_id=51&customer_name=&customer_phone=&customer_telegram=&address_city=&adress_street_app=&address_num= HTTP/1.1" 200 25190  None
INFO:django.server:"GET /ordersearch/?time_in_sence=2024-01-04&time_in_until=2024-01-06&order_status=END&repairer_id=51&customer_name=&customer_phone=&customer_telegram=&address_city=&adress_street_app=&address_num= HTTP/1.1" 200 25190
06/Jan/2024 18:04:48   WARNING  "GET /static/js/counter.js HTTP/1.1" 404 1798  None
WARNING:django.server:"GET /static/js/counter.js HTTP/1.1" 404 1798
06/Jan/2024 18:04:50   INFO  "GET /list_order/1133 HTTP/1.1" 200 25116  None
INFO:django.server:"GET /list_order/1133 HTTP/1.1" 200 25116
06/Jan/2024 18:04:50   WARNING  "GET /static/js/counter.js HTTP/1.1" 404 1798  None
WARNING:django.server:"GET /static/js/counter.js HTTP/1.1" 404 1798
06/Jan/2024 18:04:54   INFO  "GET /list_order/1132 HTTP/1.1" 200 25133  None
INFO:django.server:"GET /list_order/1132 HTTP/1.1" 200 25133
06/Jan/2024 18:04:54   WARNING  "GET /static/js/counter.js HTTP/1.1" 404 1798  None
WARNING:django.server:"GET /static/js/counter.js HTTP/1.1" 404 1798
06/Jan/2024 18:05:00   INFO  "GET /ordersearch/?time_in_sence=2024-01-04&time_in_until=2024-01-06&order_status=END&repairer_id=51&customer_name=&customer_phone=&customer_telegram=&address_city=&adress_street_app=&address_num= HTTP/1.1" 200 25190  None
INFO:django.server:"GET /ordersearch/?time_in_sence=2024-01-04&time_in_until=2024-01-06&order_status=END&repairer_id=51&customer_name=&customer_phone=&customer_telegram=&address_city=&adress_street_app=&address_num= HTTP/1.1" 200 25190
06/Jan/2024 18:05:01   WARNING  "GET /static/js/counter.js HTTP/1.1" 404 1798  None
WARNING:django.server:"GET /static/js/counter.js HTTP/1.1" 404 1798
06/Jan/2024 18:05:02   INFO  "GET /list_order/1133 HTTP/1.1" 200 25116  None
INFO:django.server:"GET /list_order/1133 HTTP/1.1" 200 25116
06/Jan/2024 18:05:02   WARNING  "GET /static/js/counter.js HTTP/1.1" 404 1798  None
WARNING:django.server:"GET /static/js/counter.js HTTP/1.1" 404 1798
06/Jan/2024 18:05:05   INFO  "GET /list_order/1132 HTTP/1.1" 200 25133  None
INFO:django.server:"GET /list_order/1132 HTTP/1.1" 200 25133
06/Jan/2024 18:05:05   WARNING  "GET /static/js/counter.js HTTP/1.1" 404 1798  None
WARNING:django.server:"GET /static/js/counter.js HTTP/1.1" 404 1798
06/Jan/2024 18:06:15   INFO  /home/alprostov/PycharmProjects/sakhlis/sakhlis/web/app_site/views.py changed, reloading.  None
INFO:django.utils.autoreload:/home/alprostov/PycharmProjects/sakhlis/sakhlis/web/app_site/views.py changed, reloading.
06/Jan/2024 18:06:17   INFO  Watching for file changes with StatReloader  None
06/Jan/2024 18:06:19   INFO  "GET /ordersearch/?time_in_sence=2024-01-04&time_in_until=2024-01-06&order_status=END&repairer_id=51&customer_name=&customer_phone=&customer_telegram=&address_city=&adress_street_app=&address_num= HTTP/1.1" 200 25192  None
INFO:django.server:"GET /ordersearch/?time_in_sence=2024-01-04&time_in_until=2024-01-06&order_status=END&repairer_id=51&customer_name=&customer_phone=&customer_telegram=&address_city=&adress_street_app=&address_num= HTTP/1.1" 200 25192
06/Jan/2024 18:06:19   WARNING  "GET /static/js/counter.js HTTP/1.1" 404 1798  None
WARNING:django.server:"GET /static/js/counter.js HTTP/1.1" 404 1798
06/Jan/2024 18:06:23   INFO  "GET /ordersearch/?time_in_sence=2024-01-04&time_in_until=2024-01-06&order_status=&repairer_id=51&customer_name=&customer_phone=&customer_telegram=&address_city=&adress_street_app=&address_num= HTTP/1.1" 200 29854  None
INFO:django.server:"GET /ordersearch/?time_in_sence=2024-01-04&time_in_until=2024-01-06&order_status=&repairer_id=51&customer_name=&customer_phone=&customer_telegram=&address_city=&adress_street_app=&address_num= HTTP/1.1" 200 29854
06/Jan/2024 18:06:23   WARNING  "GET /static/js/counter.js HTTP/1.1" 404 1798  None
WARNING:django.server:"GET /static/js/counter.js HTTP/1.1" 404 1798
06/Jan/2024 18:06:31   INFO  "GET /ordersearch/?time_in_sence=&time_in_until=&order_status=&repairer_id=51&customer_name=&customer_phone=&customer_telegram=&address_city=&adress_street_app=&address_num= HTTP/1.1" 200 55840  None
INFO:django.server:"GET /ordersearch/?time_in_sence=&time_in_until=&order_status=&repairer_id=51&customer_name=&customer_phone=&customer_telegram=&address_city=&adress_street_app=&address_num= HTTP/1.1" 200 55840
06/Jan/2024 18:06:31   WARNING  "GET /static/js/counter.js HTTP/1.1" 404 1798  None
WARNING:django.server:"GET /static/js/counter.js HTTP/1.1" 404 1798
06/Jan/2024 18:06:33   INFO  "GET /user/51 HTTP/1.1" 200 16064  None
INFO:django.server:"GET /user/51 HTTP/1.1" 200 16064
06/Jan/2024 18:06:33   WARNING  "GET /static/js/counter.js HTTP/1.1" 404 1798  None
WARNING:django.server:"GET /static/js/counter.js HTTP/1.1" 404 1798
06/Jan/2024 18:06:39   INFO  "GET /ordersearch/ HTTP/1.1" 200 55631  None
INFO:django.server:"GET /ordersearch/ HTTP/1.1" 200 55631
06/Jan/2024 18:06:39   WARNING  "GET /static/js/counter.js HTTP/1.1" 404 1798  None
WARNING:django.server:"GET /static/js/counter.js HTTP/1.1" 404 1798
06/Jan/2024 18:06:43   INFO  "GET /ordersearch/?time_in_sence=&time_in_until=&order_status=RCV&repairer_id=51&customer_name=&customer_phone=&customer_telegram=&address_city=&adress_street_app=&address_num= HTTP/1.1" 200 30006  None
INFO:django.server:"GET /ordersearch/?time_in_sence=&time_in_until=&order_status=RCV&repairer_id=51&customer_name=&customer_phone=&customer_telegram=&address_city=&adress_street_app=&address_num= HTTP/1.1" 200 30006
06/Jan/2024 18:06:43   WARNING  "GET /static/js/counter.js HTTP/1.1" 404 1798  None
WARNING:django.server:"GET /static/js/counter.js HTTP/1.1" 404 1798
06/Jan/2024 18:06:47   INFO  "GET /ordersearch/?time_in_sence=&time_in_until=&order_status=END&repairer_id=51&customer_name=&customer_phone=&customer_telegram=&address_city=&adress_street_app=&address_num= HTTP/1.1" 200 56113  None
INFO:django.server:"GET /ordersearch/?time_in_sence=&time_in_until=&order_status=END&repairer_id=51&customer_name=&customer_phone=&customer_telegram=&address_city=&adress_street_app=&address_num= HTTP/1.1" 200 56113
06/Jan/2024 18:06:47   WARNING  "GET /static/js/counter.js HTTP/1.1" 404 1798  None
WARNING:django.server:"GET /static/js/counter.js HTTP/1.1" 404 1798
06/Jan/2024 18:06:54   INFO  "GET /ordersearch/?time_in_sence=&time_in_until=&order_status=END&repairer_id=51&customer_name=&customer_phone=&customer_telegram=&address_city=&adress_street_app=%D0%9F%D0%BE%D0%BB&address_num= HTTP/1.1" 200 32554  None
INFO:django.server:"GET /ordersearch/?time_in_sence=&time_in_until=&order_status=END&repairer_id=51&customer_name=&customer_phone=&customer_telegram=&address_city=&adress_street_app=%D0%9F%D0%BE%D0%BB&address_num= HTTP/1.1" 200 32554
06/Jan/2024 18:06:54   WARNING  "GET /static/js/counter.js HTTP/1.1" 404 1798  None
WARNING:django.server:"GET /static/js/counter.js HTTP/1.1" 404 1798
06/Jan/2024 18:07:07   INFO  "GET /ordersearch/?time_in_sence=&time_in_until=&order_status=END&repairer_id=51&customer_name=&customer_phone=&customer_telegram=&address_city=&adress_street_app=%D0%90%D0%B1%D0%B0%D1%88&address_num= HTTP/1.1" 200 37172  None
INFO:django.server:"GET /ordersearch/?time_in_sence=&time_in_until=&order_status=END&repairer_id=51&customer_name=&customer_phone=&customer_telegram=&address_city=&adress_street_app=%D0%90%D0%B1%D0%B0%D1%88&address_num= HTTP/1.1" 200 37172
06/Jan/2024 18:07:07   WARNING  "GET /static/js/counter.js HTTP/1.1" 404 1798  None
WARNING:django.server:"GET /static/js/counter.js HTTP/1.1" 404 1798
06/Jan/2024 18:07:19   INFO  "GET /ordersearch/?time_in_sence=&time_in_until=&order_status=END&repairer_id=51&customer_name=%D0%9C%D0%B0%D1%82%D0%B2%D0%B5%D0%B9&customer_phone=&customer_telegram=&address_city=&adress_street_app=%D0%90%D0%B1%D0%B0%D1%88&address_num= HTTP/1.1" 200 30172  None
INFO:django.server:"GET /ordersearch/?time_in_sence=&time_in_until=&order_status=END&repairer_id=51&customer_name=%D0%9C%D0%B0%D1%82%D0%B2%D0%B5%D0%B9&customer_phone=&customer_telegram=&address_city=&adress_street_app=%D0%90%D0%B1%D0%B0%D1%88&address_num= HTTP/1.1" 200 30172
06/Jan/2024 18:07:19   WARNING  "GET /static/js/counter.js HTTP/1.1" 404 1798  None
WARNING:django.server:"GET /static/js/counter.js HTTP/1.1" 404 1798
06/Jan/2024 18:07:31   INFO  "GET /ordersearch/?time_in_sence=&time_in_until=&order_status=END&repairer_id=51&customer_name=&customer_phone=&customer_telegram=&address_city=&adress_street_app=&address_num= HTTP/1.1" 200 56113  None
INFO:django.server:"GET /ordersearch/?time_in_sence=&time_in_until=&order_status=END&repairer_id=51&customer_name=&customer_phone=&customer_telegram=&address_city=&adress_street_app=&address_num= HTTP/1.1" 200 56113
06/Jan/2024 18:07:31   WARNING  "GET /static/js/counter.js HTTP/1.1" 404 1798  None
WARNING:django.server:"GET /static/js/counter.js HTTP/1.1" 404 1798
06/Jan/2024 18:07:42   INFO  "GET /ordersearch/?page=2 HTTP/1.1" 200 56363  None
INFO:django.server:"GET /ordersearch/?page=2 HTTP/1.1" 200 56363
06/Jan/2024 18:07:42   WARNING  "GET /static/js/counter.js HTTP/1.1" 404 1798  None
WARNING:django.server:"GET /static/js/counter.js HTTP/1.1" 404 1798
06/Jan/2024 18:07:47   INFO  "GET /ordersearch/?page=1 HTTP/1.1" 200 55638  None
INFO:django.server:"GET /ordersearch/?page=1 HTTP/1.1" 200 55638
06/Jan/2024 18:07:47   WARNING  "GET /static/js/counter.js HTTP/1.1" 404 1798  None
WARNING:django.server:"GET /static/js/counter.js HTTP/1.1" 404 1798
06/Jan/2024 18:07:55   INFO  "GET /ordersearch/?time_in_sence=&time_in_until=&order_status=RCV&repairer_id=51&customer_name=&customer_phone=&customer_telegram=&address_city=&adress_street_app=&address_num= HTTP/1.1" 200 30006  None
INFO:django.server:"GET /ordersearch/?time_in_sence=&time_in_until=&order_status=RCV&repairer_id=51&customer_name=&customer_phone=&customer_telegram=&address_city=&adress_street_app=&address_num= HTTP/1.1" 200 30006
06/Jan/2024 18:07:55   WARNING  "GET /static/js/counter.js HTTP/1.1" 404 1798  None
WARNING:django.server:"GET /static/js/counter.js HTTP/1.1" 404 1798
06/Jan/2024 18:08:01   INFO  "GET /ordersearch/?time_in_sence=&time_in_until=&order_status=END&repairer_id=51&customer_name=&customer_phone=&customer_telegram=&address_city=&adress_street_app=&address_num= HTTP/1.1" 200 56112  None
INFO:django.server:"GET /ordersearch/?time_in_sence=&time_in_until=&order_status=END&repairer_id=51&customer_name=&customer_phone=&customer_telegram=&address_city=&adress_street_app=&address_num= HTTP/1.1" 200 56112
06/Jan/2024 18:08:01   WARNING  "GET /static/js/counter.js HTTP/1.1" 404 1798  None
WARNING:django.server:"GET /static/js/counter.js HTTP/1.1" 404 1798
06/Jan/2024 18:08:05   INFO  "GET /ordersearch/?page=2 HTTP/1.1" 200 56363  None
INFO:django.server:"GET /ordersearch/?page=2 HTTP/1.1" 200 56363
06/Jan/2024 18:08:05   WARNING  "GET /static/js/counter.js HTTP/1.1" 404 1798  None
WARNING:django.server:"GET /static/js/counter.js HTTP/1.1" 404 1798
06/Jan/2024 18:09:33   INFO  "GET /ordersearch/?time_in_sence=&time_in_until=&order_status=END&repairer_id=51&customer_name=&customer_phone=&customer_telegram=&address_city=&adress_street_app=&address_num= HTTP/1.1" 200 56170  None
INFO:django.server:"GET /ordersearch/?time_in_sence=&time_in_until=&order_status=END&repairer_id=51&customer_name=&customer_phone=&customer_telegram=&address_city=&adress_street_app=&address_num= HTTP/1.1" 200 56170
06/Jan/2024 18:09:33   WARNING  "GET /static/js/counter.js HTTP/1.1" 404 1798  None
WARNING:django.server:"GET /static/js/counter.js HTTP/1.1" 404 1798
06/Jan/2024 18:09:41   INFO  "GET /ordersearch/?time_in_sence=&time_in_until=&order_status=END&repairer_id=51&customer_name=&customer_phone=&customer_telegram=&address_city=&adress_street_app=&address_num= HTTP/1.1" 200 56171  None
INFO:django.server:"GET /ordersearch/?time_in_sence=&time_in_until=&order_status=END&repairer_id=51&customer_name=&customer_phone=&customer_telegram=&address_city=&adress_street_app=&address_num= HTTP/1.1" 200 56171
06/Jan/2024 18:09:41   WARNING  "GET /static/js/counter.js HTTP/1.1" 404 1798  None
WARNING:django.server:"GET /static/js/counter.js HTTP/1.1" 404 1798
06/Jan/2024 18:10:06   INFO  "GET /__debug__/render_panel/?store_id=b499f02a0d38456bb2e33e739b6f7117&panel_id=SQLPanel HTTP/1.1" 200 1600485  None
INFO:django.server:"GET /__debug__/render_panel/?store_id=b499f02a0d38456bb2e33e739b6f7117&panel_id=SQLPanel HTTP/1.1" 200 1600485
06/Jan/2024 18:10:31   INFO  "GET /ordersearch/?time_in_sence=2024-01-01&time_in_until=&order_status=END&repairer_id=51&customer_name=&customer_phone=&customer_telegram=&address_city=&adress_street_app=&address_num= HTTP/1.1" 200 34715  None
INFO:django.server:"GET /ordersearch/?time_in_sence=2024-01-01&time_in_until=&order_status=END&repairer_id=51&customer_name=&customer_phone=&customer_telegram=&address_city=&adress_street_app=&address_num= HTTP/1.1" 200 34715
06/Jan/2024 18:10:31   WARNING  "GET /static/js/counter.js HTTP/1.1" 404 1798  None
WARNING:django.server:"GET /static/js/counter.js HTTP/1.1" 404 1798
06/Jan/2024 18:10:34   INFO  "GET /__debug__/render_panel/?store_id=04e6b0dfd7294b97a243a64a389ec71b&panel_id=SQLPanel HTTP/1.1" 200 106827  None
INFO:django.server:"GET /__debug__/render_panel/?store_id=04e6b0dfd7294b97a243a64a389ec71b&panel_id=SQLPanel HTTP/1.1" 200 106827
06/Jan/2024 18:27:05   INFO  /home/alprostov/PycharmProjects/sakhlis/sakhlis/web/app_site/views.py changed, reloading.  None
INFO:django.utils.autoreload:/home/alprostov/PycharmProjects/sakhlis/sakhlis/web/app_site/views.py changed, reloading.
06/Jan/2024 18:27:07   INFO  Watching for file changes with StatReloader  None
06/Jan/2024 18:27:08   INFO  "GET /ordersearch/?time_in_sence=2024-01-01&time_in_until=&order_status=END&repairer_id=51&customer_name=&customer_phone=&customer_telegram=&address_city=&adress_street_app=&address_num= HTTP/1.1" 200 34716  None
INFO:django.server:"GET /ordersearch/?time_in_sence=2024-01-01&time_in_until=&order_status=END&repairer_id=51&customer_name=&customer_phone=&customer_telegram=&address_city=&adress_street_app=&address_num= HTTP/1.1" 200 34716
06/Jan/2024 18:27:08   WARNING  "GET /static/js/counter.js HTTP/1.1" 404 1798  None
WARNING:django.server:"GET /static/js/counter.js HTTP/1.1" 404 1798
06/Jan/2024 18:27:10   INFO  "GET /ordersearch/?time_in_sence=2024-01-01&time_in_until=&order_status=END&repairer_id=51&customer_name=&customer_phone=&customer_telegram=&address_city=&adress_street_app=&address_num= HTTP/1.1" 200 34714  None
INFO:django.server:"GET /ordersearch/?time_in_sence=2024-01-01&time_in_until=&order_status=END&repairer_id=51&customer_name=&customer_phone=&customer_telegram=&address_city=&adress_street_app=&address_num= HTTP/1.1" 200 34714
06/Jan/2024 18:27:10   WARNING  "GET /static/js/counter.js HTTP/1.1" 404 1798  None
WARNING:django.server:"GET /static/js/counter.js HTTP/1.1" 404 1798
06/Jan/2024 18:27:12   INFO  "GET /__debug__/render_panel/?store_id=d8835d4ac8d74a0da3df11105fa9bf56&panel_id=SQLPanel HTTP/1.1" 200 61210  None
INFO:django.server:"GET /__debug__/render_panel/?store_id=d8835d4ac8d74a0da3df11105fa9bf56&panel_id=SQLPanel HTTP/1.1" 200 61210
06/Jan/2024 18:27:22   INFO  "GET /ordersearch/?time_in_sence=2024-01-04&time_in_until=&order_status=END&repairer_id=51&customer_name=&customer_phone=&customer_telegram=&address_city=&adress_street_app=&address_num= HTTP/1.1" 200 25228  None
INFO:django.server:"GET /ordersearch/?time_in_sence=2024-01-04&time_in_until=&order_status=END&repairer_id=51&customer_name=&customer_phone=&customer_telegram=&address_city=&adress_street_app=&address_num= HTTP/1.1" 200 25228
06/Jan/2024 18:27:22   WARNING  "GET /static/js/counter.js HTTP/1.1" 404 1798  None
WARNING:django.server:"GET /static/js/counter.js HTTP/1.1" 404 1798
06/Jan/2024 18:27:31   INFO  "GET /ordersearch/?time_in_sence=&time_in_until=&order_status=END&repairer_id=51&customer_name=&customer_phone=&customer_telegram=&address_city=&adress_street_app=&address_num= HTTP/1.1" 200 56166  None
INFO:django.server:"GET /ordersearch/?time_in_sence=&time_in_until=&order_status=END&repairer_id=51&customer_name=&customer_phone=&customer_telegram=&address_city=&adress_street_app=&address_num= HTTP/1.1" 200 56166
06/Jan/2024 18:27:31   WARNING  "GET /static/js/counter.js HTTP/1.1" 404 1798  None
WARNING:django.server:"GET /static/js/counter.js HTTP/1.1" 404 1798
06/Jan/2024 18:27:36   INFO  "GET /user/51 HTTP/1.1" 200 16064  None
INFO:django.server:"GET /user/51 HTTP/1.1" 200 16064
06/Jan/2024 18:27:36   WARNING  "GET /static/js/counter.js HTTP/1.1" 404 1798  None
WARNING:django.server:"GET /static/js/counter.js HTTP/1.1" 404 1798
06/Jan/2024 18:27:59   INFO  "GET /ordersearch/?time_in_sence=&time_in_until=&order_status=END&repairer_id=51&customer_name=%D0%9C%D0%B0%D1%82%D0%B2%D0%B5%D0%B9&customer_phone=&customer_telegram=&address_city=&adress_street_app=&address_num= HTTP/1.1" 200 30189  None
INFO:django.server:"GET /ordersearch/?time_in_sence=&time_in_until=&order_status=END&repairer_id=51&customer_name=%D0%9C%D0%B0%D1%82%D0%B2%D0%B5%D0%B9&customer_phone=&customer_telegram=&address_city=&adress_street_app=&address_num= HTTP/1.1" 200 30189
06/Jan/2024 18:27:59   WARNING  "GET /static/js/counter.js HTTP/1.1" 404 1798  None
WARNING:django.server:"GET /static/js/counter.js HTTP/1.1" 404 1798
06/Jan/2024 18:30:57   INFO  /home/alprostov/PycharmProjects/sakhlis/sakhlis/web/app_site/views.py changed, reloading.  None
INFO:django.utils.autoreload:/home/alprostov/PycharmProjects/sakhlis/sakhlis/web/app_site/views.py changed, reloading.
06/Jan/2024 18:30:59   INFO  Watching for file changes with StatReloader  None
06/Jan/2024 18:31:02   INFO  "GET /ordersearch/?time_in_sence=&time_in_until=&order_status=END&repairer_id=51&customer_name=%D0%9C%D0%B0%D1%82%D0%B2%D0%B5%D0%B9&customer_phone=&customer_telegram=&address_city=&adress_street_app=&address_num= HTTP/1.1" 200 30228  None
INFO:django.server:"GET /ordersearch/?time_in_sence=&time_in_until=&order_status=END&repairer_id=51&customer_name=%D0%9C%D0%B0%D1%82%D0%B2%D0%B5%D0%B9&customer_phone=&customer_telegram=&address_city=&adress_street_app=&address_num= HTTP/1.1" 200 30228
06/Jan/2024 18:31:02   WARNING  "GET /static/js/counter.js HTTP/1.1" 404 1798  None
WARNING:django.server:"GET /static/js/counter.js HTTP/1.1" 404 1798
06/Jan/2024 18:31:13   INFO  "GET /ordersearch/?time_in_sence=&time_in_until=&order_status=&repairer_id=51&customer_name=%D0%9C%D0%B0%D1%82%D0%B2%D0%B5%D0%B9&customer_phone=&customer_telegram=&address_city=&adress_street_app=&address_num= HTTP/1.1" 200 30223  None
INFO:django.server:"GET /ordersearch/?time_in_sence=&time_in_until=&order_status=&repairer_id=51&customer_name=%D0%9C%D0%B0%D1%82%D0%B2%D0%B5%D0%B9&customer_phone=&customer_telegram=&address_city=&adress_street_app=&address_num= HTTP/1.1" 200 30223
06/Jan/2024 18:31:13   WARNING  "GET /static/js/counter.js HTTP/1.1" 404 1798  None
WARNING:django.server:"GET /static/js/counter.js HTTP/1.1" 404 1798
06/Jan/2024 18:31:17   INFO  "GET /ordersearch/?time_in_sence=&time_in_until=&order_status=&repairer_id=51&customer_name=&customer_phone=&customer_telegram=&address_city=&adress_street_app=&address_num= HTTP/1.1" 200 55932  None
INFO:django.server:"GET /ordersearch/?time_in_sence=&time_in_until=&order_status=&repairer_id=51&customer_name=&customer_phone=&customer_telegram=&address_city=&adress_street_app=&address_num= HTTP/1.1" 200 55932
06/Jan/2024 18:31:17   WARNING  "GET /static/js/counter.js HTTP/1.1" 404 1798  None
WARNING:django.server:"GET /static/js/counter.js HTTP/1.1" 404 1798
06/Jan/2024 18:31:20   INFO  "GET /user/51 HTTP/1.1" 200 16064  None
INFO:django.server:"GET /user/51 HTTP/1.1" 200 16064
06/Jan/2024 18:31:20   WARNING  "GET /static/js/counter.js HTTP/1.1" 404 1798  None
WARNING:django.server:"GET /static/js/counter.js HTTP/1.1" 404 1798
06/Jan/2024 18:31:25   INFO  "GET /list_order?work_status=END HTTP/1.1" 200 53766  None
INFO:django.server:"GET /list_order?work_status=END HTTP/1.1" 200 53766
06/Jan/2024 18:31:25   WARNING  "GET /static/js/counter.js HTTP/1.1" 404 1798  None
WARNING:django.server:"GET /static/js/counter.js HTTP/1.1" 404 1798
06/Jan/2024 18:31:27   INFO  "GET /ordersearch/ HTTP/1.1" 200 55723  None
INFO:django.server:"GET /ordersearch/ HTTP/1.1" 200 55723
06/Jan/2024 18:31:27   WARNING  "GET /static/js/counter.js HTTP/1.1" 404 1798  None
WARNING:django.server:"GET /static/js/counter.js HTTP/1.1" 404 1798
06/Jan/2024 18:31:43   INFO  "GET /ordersearch/?time_in_sence=&time_in_until=&order_status=&repairer_id=51&customer_name=&customer_phone=&customer_telegram=&address_city=&adress_street_app=%D0%9F%D0%B5%D0%BA%D0%B8%D0%BD%D0%B0&address_num= HTTP/1.1" 200 32349  None
INFO:django.server:"GET /ordersearch/?time_in_sence=&time_in_until=&order_status=&repairer_id=51&customer_name=&customer_phone=&customer_telegram=&address_city=&adress_street_app=%D0%9F%D0%B5%D0%BA%D0%B8%D0%BD%D0%B0&address_num= HTTP/1.1" 200 32349
06/Jan/2024 18:31:43   WARNING  "GET /static/js/counter.js HTTP/1.1" 404 1798  None
WARNING:django.server:"GET /static/js/counter.js HTTP/1.1" 404 1798
06/Jan/2024 18:32:30   INFO  "GET /user/51 HTTP/1.1" 200 16064  None
INFO:django.server:"GET /user/51 HTTP/1.1" 200 16064
06/Jan/2024 18:32:30   WARNING  "GET /static/js/counter.js HTTP/1.1" 404 1798  None
WARNING:django.server:"GET /static/js/counter.js HTTP/1.1" 404 1798
06/Jan/2024 18:32:34   INFO  "GET /list_order?work_status=END HTTP/1.1" 200 53766  None
INFO:django.server:"GET /list_order?work_status=END HTTP/1.1" 200 53766
06/Jan/2024 18:32:34   WARNING  "GET /static/js/counter.js HTTP/1.1" 404 1798  None
WARNING:django.server:"GET /static/js/counter.js HTTP/1.1" 404 1798
06/Jan/2024 18:32:37   INFO  "GET /stat/ HTTP/1.1" 200 190351  None
INFO:django.server:"GET /stat/ HTTP/1.1" 200 190351
06/Jan/2024 18:32:37   WARNING  "GET /static/js/counter.js HTTP/1.1" 404 1798  None
WARNING:django.server:"GET /static/js/counter.js HTTP/1.1" 404 1798
06/Jan/2024 18:33:02   INFO  "GET /list_order HTTP/1.1" 200 53814  None
INFO:django.server:"GET /list_order HTTP/1.1" 200 53814
06/Jan/2024 18:33:02   WARNING  "GET /static/js/counter.js HTTP/1.1" 404 1798  None
WARNING:django.server:"GET /static/js/counter.js HTTP/1.1" 404 1798
06/Jan/2024 18:33:05   INFO  "GET /user/51 HTTP/1.1" 200 16064  None
INFO:django.server:"GET /user/51 HTTP/1.1" 200 16064
06/Jan/2024 18:33:05   WARNING  "GET /static/js/counter.js HTTP/1.1" 404 1798  None
WARNING:django.server:"GET /static/js/counter.js HTTP/1.1" 404 1798
06/Jan/2024 18:33:17   INFO  "GET /stat/ HTTP/1.1" 200 190351  None
INFO:django.server:"GET /stat/ HTTP/1.1" 200 190351
06/Jan/2024 18:33:17   WARNING  "GET /static/js/counter.js HTTP/1.1" 404 1798  None
WARNING:django.server:"GET /static/js/counter.js HTTP/1.1" 404 1798
06/Jan/2024 18:33:19   INFO  "GET /list_order HTTP/1.1" 200 53814  None
INFO:django.server:"GET /list_order HTTP/1.1" 200 53814
06/Jan/2024 18:33:19   WARNING  "GET /static/js/counter.js HTTP/1.1" 404 1798  None
WARNING:django.server:"GET /static/js/counter.js HTTP/1.1" 404 1798
06/Jan/2024 18:33:20   INFO  "GET / HTTP/1.1" 200 43209  None
INFO:django.server:"GET / HTTP/1.1" 200 43209
06/Jan/2024 18:33:20   WARNING  "GET /static/js/counter.js HTTP/1.1" 404 1798  None
WARNING:django.server:"GET /static/js/counter.js HTTP/1.1" 404 1798
06/Jan/2024 18:33:24   INFO  "GET /list_order HTTP/1.1" 200 53814  None
INFO:django.server:"GET /list_order HTTP/1.1" 200 53814
06/Jan/2024 18:33:24   WARNING  "GET /static/js/counter.js HTTP/1.1" 404 1798  None
WARNING:django.server:"GET /static/js/counter.js HTTP/1.1" 404 1798
06/Jan/2024 18:33:27   INFO  "GET /ordersearch/ HTTP/1.1" 200 55723  None
INFO:django.server:"GET /ordersearch/ HTTP/1.1" 200 55723
06/Jan/2024 18:33:27   WARNING  "GET /static/js/counter.js HTTP/1.1" 404 1798  None
WARNING:django.server:"GET /static/js/counter.js HTTP/1.1" 404 1798
06/Jan/2024 18:33:29   INFO  "GET /__debug__/render_panel/?store_id=399a5fa3ff504cf99db8f6b112c15afe&panel_id=SQLPanel HTTP/1.1" 200 65740  None
INFO:django.server:"GET /__debug__/render_panel/?store_id=399a5fa3ff504cf99db8f6b112c15afe&panel_id=SQLPanel HTTP/1.1" 200 65740
06/Jan/2024 18:34:49   INFO  /home/alprostov/PycharmProjects/sakhlis/sakhlis/web/app_site/views.py changed, reloading.  None
INFO:django.utils.autoreload:/home/alprostov/PycharmProjects/sakhlis/sakhlis/web/app_site/views.py changed, reloading.
06/Jan/2024 18:34:51   INFO  Watching for file changes with StatReloader  None
06/Jan/2024 18:34:53   INFO  "GET /ordersearch/ HTTP/1.1" 200 55725  None
INFO:django.server:"GET /ordersearch/ HTTP/1.1" 200 55725
06/Jan/2024 18:34:53   WARNING  "GET /static/js/counter.js HTTP/1.1" 404 1798  None
WARNING:django.server:"GET /static/js/counter.js HTTP/1.1" 404 1798
06/Jan/2024 18:34:54   INFO  "GET /ordersearch/ HTTP/1.1" 200 55723  None
INFO:django.server:"GET /ordersearch/ HTTP/1.1" 200 55723
06/Jan/2024 18:34:54   WARNING  "GET /static/js/counter.js HTTP/1.1" 404 1798  None
WARNING:django.server:"GET /static/js/counter.js HTTP/1.1" 404 1798
06/Jan/2024 18:34:56   INFO  "GET /__debug__/render_panel/?store_id=6aeabac1044644b99a4ac6d66fda38b0&panel_id=SQLPanel HTTP/1.1" 200 65737  None
INFO:django.server:"GET /__debug__/render_panel/?store_id=6aeabac1044644b99a4ac6d66fda38b0&panel_id=SQLPanel HTTP/1.1" 200 65737
06/Jan/2024 18:35:11   INFO  /home/alprostov/PycharmProjects/sakhlis/sakhlis/web/app_site/views.py changed, reloading.  None
INFO:django.utils.autoreload:/home/alprostov/PycharmProjects/sakhlis/sakhlis/web/app_site/views.py changed, reloading.
06/Jan/2024 18:35:12   INFO  Watching for file changes with StatReloader  None
06/Jan/2024 18:35:13   INFO  "GET /list_order?work_status=RCV HTTP/1.1" 200 30213  None
INFO:django.server:"GET /list_order?work_status=RCV HTTP/1.1" 200 30213
06/Jan/2024 18:35:13   WARNING  "GET /static/js/counter.js HTTP/1.1" 404 1798  None
WARNING:django.server:"GET /static/js/counter.js HTTP/1.1" 404 1798
06/Jan/2024 18:35:14   INFO  "GET / HTTP/1.1" 200 43209  None
INFO:django.server:"GET / HTTP/1.1" 200 43209
06/Jan/2024 18:35:14   WARNING  "GET /static/js/counter.js HTTP/1.1" 404 1798  None
WARNING:django.server:"GET /static/js/counter.js HTTP/1.1" 404 1798
06/Jan/2024 22:11:18   INFO  Watching for file changes with StatReloader  None
06/Jan/2024 22:11:21   INFO  "GET /list_order HTTP/1.1" 200 53816  None
INFO:django.server:"GET /list_order HTTP/1.1" 200 53816
06/Jan/2024 22:11:21   INFO  "GET /static/css/fonts.css HTTP/1.1" 200 68940  None
INFO:django.server:"GET /static/css/fonts.css HTTP/1.1" 200 68940
06/Jan/2024 22:11:21   INFO  "GET /static/css/mdb.min.css HTTP/1.1" 200 254562  None
INFO:django.server:"GET /static/css/mdb.min.css HTTP/1.1" 200 254562
06/Jan/2024 22:11:21   INFO  "GET /static/css/bootstrap.min.css HTTP/1.1" 200 140936  None
INFO:django.server:"GET /static/css/bootstrap.min.css HTTP/1.1" 200 140936
06/Jan/2024 22:11:21   INFO  "GET /static/css/custom.css HTTP/1.1" 304 0  None
INFO:django.server:"GET /static/css/custom.css HTTP/1.1" 304 0
06/Jan/2024 22:11:21   INFO  "GET /static/js/mdb.min.js HTTP/1.1" 200 207332  None
INFO:django.server:"GET /static/js/mdb.min.js HTTP/1.1" 200 207332
06/Jan/2024 22:11:21   WARNING  "GET /static/js/counter.js HTTP/1.1" 404 1798  None
WARNING:django.server:"GET /static/js/counter.js HTTP/1.1" 404 1798
06/Jan/2024 22:11:21   INFO  "GET /static/images/master-na-chas_1.jpg HTTP/1.1" 200 323239  None
INFO:django.server:"GET /static/images/master-na-chas_1.jpg HTTP/1.1" 200 323239
06/Jan/2024 22:11:22   INFO  "GET /static/fonts/fa-solid-900.woff2 HTTP/1.1" 200 74256  None
INFO:django.server:"GET /static/fonts/fa-solid-900.woff2 HTTP/1.1" 200 74256
06/Jan/2024 22:11:25   INFO  "GET /ordersearch/ HTTP/1.1" 200 55723  None
INFO:django.server:"GET /ordersearch/ HTTP/1.1" 200 55723
06/Jan/2024 22:11:25   WARNING  "GET /static/js/counter.js HTTP/1.1" 404 1798  None
WARNING:django.server:"GET /static/js/counter.js HTTP/1.1" 404 1798
06/Jan/2024 22:11:38   INFO  "GET /ordersearch/?time_in_sence=2024-01-01&time_in_until=&order_status=SND&repairer_id=51&customer_name=&customer_phone=&customer_telegram=&address_city=&adress_street_app=&address_num= HTTP/1.1" 200 20575  None
INFO:django.server:"GET /ordersearch/?time_in_sence=2024-01-01&time_in_until=&order_status=SND&repairer_id=51&customer_name=&customer_phone=&customer_telegram=&address_city=&adress_street_app=&address_num= HTTP/1.1" 200 20575
06/Jan/2024 22:11:38   WARNING  "GET /static/js/counter.js HTTP/1.1" 404 1798  None
WARNING:django.server:"GET /static/js/counter.js HTTP/1.1" 404 1798
06/Jan/2024 22:11:43   INFO  "GET /ordersearch/?time_in_sence=2024-01-01&time_in_until=&order_status=&repairer_id=51&customer_name=&customer_phone=&customer_telegram=&address_city=&adress_street_app=&address_num= HTTP/1.1" 200 39415  None
INFO:django.server:"GET /ordersearch/?time_in_sence=2024-01-01&time_in_until=&order_status=&repairer_id=51&customer_name=&customer_phone=&customer_telegram=&address_city=&adress_street_app=&address_num= HTTP/1.1" 200 39415
06/Jan/2024 22:11:43   WARNING  "GET /static/js/counter.js HTTP/1.1" 404 1798  None
WARNING:django.server:"GET /static/js/counter.js HTTP/1.1" 404 1798
06/Jan/2024 22:11:56   INFO  "GET /ordersearch/?time_in_sence=2024-01-01&time_in_until=&order_status=RCV&repairer_id=51&customer_name=&customer_phone=&customer_telegram=&address_city=&adress_street_app=&address_num= HTTP/1.1" 200 25242  None
INFO:django.server:"GET /ordersearch/?time_in_sence=2024-01-01&time_in_until=&order_status=RCV&repairer_id=51&customer_name=&customer_phone=&customer_telegram=&address_city=&adress_street_app=&address_num= HTTP/1.1" 200 25242
06/Jan/2024 22:11:56   WARNING  "GET /static/js/counter.js HTTP/1.1" 404 1798  None
WARNING:django.server:"GET /static/js/counter.js HTTP/1.1" 404 1798
06/Jan/2024 22:12:04   INFO  "GET /ordersearch/?time_in_sence=2024-01-01&time_in_until=&order_status=END&repairer_id=51&customer_name=&customer_phone=&customer_telegram=&address_city=&adress_street_app=&address_num= HTTP/1.1" 200 34751  None
INFO:django.server:"GET /ordersearch/?time_in_sence=2024-01-01&time_in_until=&order_status=END&repairer_id=51&customer_name=&customer_phone=&customer_telegram=&address_city=&adress_street_app=&address_num= HTTP/1.1" 200 34751
06/Jan/2024 22:12:04   WARNING  "GET /static/js/counter.js HTTP/1.1" 404 1798  None
WARNING:django.server:"GET /static/js/counter.js HTTP/1.1" 404 1798
06/Jan/2024 22:12:17   INFO  "GET /ordersearch/?time_in_sence=2024-01-01&time_in_until=&order_status=END&repairer_id=51&customer_name=&customer_phone=&customer_telegram=&address_city=&adress_street_app=&address_num= HTTP/1.1" 200 34751  None
INFO:django.server:"GET /ordersearch/?time_in_sence=2024-01-01&time_in_until=&order_status=END&repairer_id=51&customer_name=&customer_phone=&customer_telegram=&address_city=&adress_street_app=&address_num= HTTP/1.1" 200 34751
06/Jan/2024 22:12:17   WARNING  "GET /static/js/counter.js HTTP/1.1" 404 1798  None
WARNING:django.server:"GET /static/js/counter.js HTTP/1.1" 404 1798
06/Jan/2024 22:12:38   INFO  "GET /ordersearch/?time_in_sence=2024-01-01&time_in_until=&order_status=END&repairer_id=51&customer_name=&customer_phone=&customer_telegram=&address_city=&adress_street_app=&address_num= HTTP/1.1" 200 34744  None
INFO:django.server:"GET /ordersearch/?time_in_sence=2024-01-01&time_in_until=&order_status=END&repairer_id=51&customer_name=&customer_phone=&customer_telegram=&address_city=&adress_street_app=&address_num= HTTP/1.1" 200 34744
06/Jan/2024 22:12:39   WARNING  "GET /static/js/counter.js HTTP/1.1" 404 1798  None
WARNING:django.server:"GET /static/js/counter.js HTTP/1.1" 404 1798
06/Jan/2024 22:13:02   INFO  "GET /ordersearch/?time_in_sence=2023-12-01&time_in_until=2023-12-31&order_status=END&repairer_id=51&customer_name=&customer_phone=&customer_telegram=&address_city=&adress_street_app=&address_num= HTTP/1.1" 200 56250  None
INFO:django.server:"GET /ordersearch/?time_in_sence=2023-12-01&time_in_until=2023-12-31&order_status=END&repairer_id=51&customer_name=&customer_phone=&customer_telegram=&address_city=&adress_street_app=&address_num= HTTP/1.1" 200 56250
06/Jan/2024 22:13:02   WARNING  "GET /static/js/counter.js HTTP/1.1" 404 1798  None
WARNING:django.server:"GET /static/js/counter.js HTTP/1.1" 404 1798
06/Jan/2024 22:13:10   INFO  "GET /stat/ HTTP/1.1" 200 190352  None
INFO:django.server:"GET /stat/ HTTP/1.1" 200 190352
06/Jan/2024 22:13:11   WARNING  "GET /static/js/counter.js HTTP/1.1" 404 1798  None
WARNING:django.server:"GET /static/js/counter.js HTTP/1.1" 404 1798
06/Jan/2024 22:13:23   INFO  "GET /list_order?work_status=RCV HTTP/1.1" 200 30211  None
INFO:django.server:"GET /list_order?work_status=RCV HTTP/1.1" 200 30211
06/Jan/2024 22:13:23   WARNING  "GET /static/js/counter.js HTTP/1.1" 404 1798  None
WARNING:django.server:"GET /static/js/counter.js HTTP/1.1" 404 1798
06/Jan/2024 22:13:25   INFO  "GET /list_order?work_status=END HTTP/1.1" 200 53766  None
INFO:django.server:"GET /list_order?work_status=END HTTP/1.1" 200 53766
06/Jan/2024 22:13:25   WARNING  "GET /static/js/counter.js HTTP/1.1" 404 1798  None
WARNING:django.server:"GET /static/js/counter.js HTTP/1.1" 404 1798
06/Jan/2024 22:13:27   INFO  "GET /stat/ HTTP/1.1" 200 190350  None
INFO:django.server:"GET /stat/ HTTP/1.1" 200 190350
06/Jan/2024 22:13:27   WARNING  "GET /static/js/counter.js HTTP/1.1" 404 1798  None
WARNING:django.server:"GET /static/js/counter.js HTTP/1.1" 404 1798
06/Jan/2024 22:13:27   INFO  "GET /user/51 HTTP/1.1" 200 16066  None
INFO:django.server:"GET /user/51 HTTP/1.1" 200 16066
06/Jan/2024 22:13:27   WARNING  "GET /static/js/counter.js HTTP/1.1" 404 1798  None
WARNING:django.server:"GET /static/js/counter.js HTTP/1.1" 404 1798
06/Jan/2024 22:13:28   INFO  "GET /media/images/%D1%8F.jpeg HTTP/1.1" 200 521837  None
INFO:django.server:"GET /media/images/%D1%8F.jpeg HTTP/1.1" 200 521837
06/Jan/2024 22:13:30   INFO  "GET /ordersearch/ HTTP/1.1" 200 55716  None
INFO:django.server:"GET /ordersearch/ HTTP/1.1" 200 55716
06/Jan/2024 22:13:30   WARNING  "GET /static/js/counter.js HTTP/1.1" 404 1798  None
WARNING:django.server:"GET /static/js/counter.js HTTP/1.1" 404 1798
06/Jan/2024 22:13:38   INFO  "GET /ordersearch/?page=15 HTTP/1.1" 200 41764  None
INFO:django.server:"GET /ordersearch/?page=15 HTTP/1.1" 200 41764
06/Jan/2024 22:13:38   WARNING  "GET /static/js/counter.js HTTP/1.1" 404 1798  None
WARNING:django.server:"GET /static/js/counter.js HTTP/1.1" 404 1798
06/Jan/2024 22:15:40   INFO  /home/alprostov/PycharmProjects/sakhlis/sakhlis/web/app_site/templatetags/custom_filters.py changed, reloading.  None
INFO:django.utils.autoreload:/home/alprostov/PycharmProjects/sakhlis/sakhlis/web/app_site/templatetags/custom_filters.py changed, reloading.
06/Jan/2024 22:15:43   INFO  Watching for file changes with StatReloader  None
06/Jan/2024 22:15:45   ERROR  Internal Server Error: /ordersearch/  (<class 'django.template.exceptions.TemplateSyntaxError'>, TemplateSyntaxError("Invalid filter: 'url_replace'"), <traceback object at 0x7f045044b640>)
Traceback (most recent call last):
  File "/home/alprostov/PycharmProjects/sakhlis/venv3/lib/python3.11/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/home/alprostov/PycharmProjects/sakhlis/venv3/lib/python3.11/site-packages/django/core/handlers/base.py", line 220, in _get_response
    response = response.render()
               ^^^^^^^^^^^^^^^^^
  File "/home/alprostov/PycharmProjects/sakhlis/venv3/lib/python3.11/site-packages/django/template/response.py", line 111, in render
    self.content = self.rendered_content
                   ^^^^^^^^^^^^^^^^^^^^^
  File "/home/alprostov/PycharmProjects/sakhlis/venv3/lib/python3.11/site-packages/django/template/response.py", line 87, in rendered_content
    template = self.resolve_template(self.template_name)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/alprostov/PycharmProjects/sakhlis/venv3/lib/python3.11/site-packages/django/template/response.py", line 69, in resolve_template
    return select_template(template, using=self.using)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/alprostov/PycharmProjects/sakhlis/venv3/lib/python3.11/site-packages/django/template/loader.py", line 42, in select_template
    return engine.get_template(template_name)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/alprostov/PycharmProjects/sakhlis/venv3/lib/python3.11/site-packages/django/template/backends/django.py", line 33, in get_template
    return Template(self.engine.get_template(template_name), self)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/alprostov/PycharmProjects/sakhlis/venv3/lib/python3.11/site-packages/django/template/engine.py", line 175, in get_template
    template, origin = self.find_template(template_name)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/alprostov/PycharmProjects/sakhlis/venv3/lib/python3.11/site-packages/django/template/engine.py", line 157, in find_template
    template = loader.get_template(name, skip=skip)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/alprostov/PycharmProjects/sakhlis/venv3/lib/python3.11/site-packages/django/template/loaders/cached.py", line 57, in get_template
    template = super().get_template(template_name, skip)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/alprostov/PycharmProjects/sakhlis/venv3/lib/python3.11/site-packages/django/template/loaders/base.py", line 28, in get_template
    return Template(
           ^^^^^^^^^
  File "/home/alprostov/PycharmProjects/sakhlis/venv3/lib/python3.11/site-packages/django/template/base.py", line 154, in __init__
    self.nodelist = self.compile_nodelist()
                    ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/alprostov/PycharmProjects/sakhlis/venv3/lib/python3.11/site-packages/django/template/base.py", line 200, in compile_nodelist
    return parser.parse()
           ^^^^^^^^^^^^^^
  File "/home/alprostov/PycharmProjects/sakhlis/venv3/lib/python3.11/site-packages/django/template/base.py", line 513, in parse
    raise self.error(token, e)
  File "/home/alprostov/PycharmProjects/sakhlis/venv3/lib/python3.11/site-packages/django/template/base.py", line 511, in parse
    compiled_result = compile_func(self, token)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/alprostov/PycharmProjects/sakhlis/venv3/lib/python3.11/site-packages/django/template/loader_tags.py", line 293, in do_extends
    nodelist = parser.parse()
               ^^^^^^^^^^^^^^
  File "/home/alprostov/PycharmProjects/sakhlis/venv3/lib/python3.11/site-packages/django/template/base.py", line 513, in parse
    raise self.error(token, e)
  File "/home/alprostov/PycharmProjects/sakhlis/venv3/lib/python3.11/site-packages/django/template/base.py", line 511, in parse
    compiled_result = compile_func(self, token)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/alprostov/PycharmProjects/sakhlis/venv3/lib/python3.11/site-packages/django/template/loader_tags.py", line 232, in do_block
    nodelist = parser.parse(("endblock",))
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/alprostov/PycharmProjects/sakhlis/venv3/lib/python3.11/site-packages/django/template/base.py", line 513, in parse
    raise self.error(token, e)
  File "/home/alprostov/PycharmProjects/sakhlis/venv3/lib/python3.11/site-packages/django/template/base.py", line 511, in parse
    compiled_result = compile_func(self, token)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/alprostov/PycharmProjects/sakhlis/venv3/lib/python3.11/site-packages/django/template/defaulttags.py", line 953, in do_if
    nodelist = parser.parse(("elif", "else", "endif"))
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/alprostov/PycharmProjects/sakhlis/venv3/lib/python3.11/site-packages/django/template/base.py", line 513, in parse
    raise self.error(token, e)
  File "/home/alprostov/PycharmProjects/sakhlis/venv3/lib/python3.11/site-packages/django/template/base.py", line 511, in parse
    compiled_result = compile_func(self, token)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/alprostov/PycharmProjects/sakhlis/venv3/lib/python3.11/site-packages/django/template/defaulttags.py", line 953, in do_if
    nodelist = parser.parse(("elif", "else", "endif"))
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/alprostov/PycharmProjects/sakhlis/venv3/lib/python3.11/site-packages/django/template/base.py", line 484, in parse
    raise self.error(token, e)
  File "/home/alprostov/PycharmProjects/sakhlis/venv3/lib/python3.11/site-packages/django/template/base.py", line 482, in parse
    filter_expression = self.compile_filter(token.contents)
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/alprostov/PycharmProjects/sakhlis/venv3/lib/python3.11/site-packages/django/template/base.py", line 600, in compile_filter
    return FilterExpression(token, self)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/alprostov/PycharmProjects/sakhlis/venv3/lib/python3.11/site-packages/django/template/base.py", line 698, in __init__
    filter_func = parser.find_filter(filter_name)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/alprostov/PycharmProjects/sakhlis/venv3/lib/python3.11/site-packages/django/template/base.py", line 606, in find_filter
    raise TemplateSyntaxError("Invalid filter: '%s'" % filter_name)
django.template.exceptions.TemplateSyntaxError: Invalid filter: 'url_replace'
ERROR:django.request:Internal Server Error: /ordersearch/
Traceback (most recent call last):
  File "/home/alprostov/PycharmProjects/sakhlis/venv3/lib/python3.11/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/home/alprostov/PycharmProjects/sakhlis/venv3/lib/python3.11/site-packages/django/core/handlers/base.py", line 220, in _get_response
    response = response.render()
               ^^^^^^^^^^^^^^^^^
  File "/home/alprostov/PycharmProjects/sakhlis/venv3/lib/python3.11/site-packages/django/template/response.py", line 111, in render
    self.content = self.rendered_content
                   ^^^^^^^^^^^^^^^^^^^^^
  File "/home/alprostov/PycharmProjects/sakhlis/venv3/lib/python3.11/site-packages/django/template/response.py", line 87, in rendered_content
    template = self.resolve_template(self.template_name)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/alprostov/PycharmProjects/sakhlis/venv3/lib/python3.11/site-packages/django/template/response.py", line 69, in resolve_template
    return select_template(template, using=self.using)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/alprostov/PycharmProjects/sakhlis/venv3/lib/python3.11/site-packages/django/template/loader.py", line 42, in select_template
    return engine.get_template(template_name)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/alprostov/PycharmProjects/sakhlis/venv3/lib/python3.11/site-packages/django/template/backends/django.py", line 33, in get_template
    return Template(self.engine.get_template(template_name), self)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/alprostov/PycharmProjects/sakhlis/venv3/lib/python3.11/site-packages/django/template/engine.py", line 175, in get_template
    template, origin = self.find_template(template_name)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/alprostov/PycharmProjects/sakhlis/venv3/lib/python3.11/site-packages/django/template/engine.py", line 157, in find_template
    template = loader.get_template(name, skip=skip)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/alprostov/PycharmProjects/sakhlis/venv3/lib/python3.11/site-packages/django/template/loaders/cached.py", line 57, in get_template
    template = super().get_template(template_name, skip)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/alprostov/PycharmProjects/sakhlis/venv3/lib/python3.11/site-packages/django/template/loaders/base.py", line 28, in get_template
    return Template(
           ^^^^^^^^^
  File "/home/alprostov/PycharmProjects/sakhlis/venv3/lib/python3.11/site-packages/django/template/base.py", line 154, in __init__
    self.nodelist = self.compile_nodelist()
                    ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/alprostov/PycharmProjects/sakhlis/venv3/lib/python3.11/site-packages/django/template/base.py", line 200, in compile_nodelist
    return parser.parse()
           ^^^^^^^^^^^^^^
  File "/home/alprostov/PycharmProjects/sakhlis/venv3/lib/python3.11/site-packages/django/template/base.py", line 513, in parse
    raise self.error(token, e)
  File "/home/alprostov/PycharmProjects/sakhlis/venv3/lib/python3.11/site-packages/django/template/base.py", line 511, in parse
    compiled_result = compile_func(self, token)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/alprostov/PycharmProjects/sakhlis/venv3/lib/python3.11/site-packages/django/template/loader_tags.py", line 293, in do_extends
    nodelist = parser.parse()
               ^^^^^^^^^^^^^^
  File "/home/alprostov/PycharmProjects/sakhlis/venv3/lib/python3.11/site-packages/django/template/base.py", line 513, in parse
    raise self.error(token, e)
  File "/home/alprostov/PycharmProjects/sakhlis/venv3/lib/python3.11/site-packages/django/template/base.py", line 511, in parse
    compiled_result = compile_func(self, token)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/alprostov/PycharmProjects/sakhlis/venv3/lib/python3.11/site-packages/django/template/loader_tags.py", line 232, in do_block
    nodelist = parser.parse(("endblock",))
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/alprostov/PycharmProjects/sakhlis/venv3/lib/python3.11/site-packages/django/template/base.py", line 513, in parse
    raise self.error(token, e)
  File "/home/alprostov/PycharmProjects/sakhlis/venv3/lib/python3.11/site-packages/django/template/base.py", line 511, in parse
    compiled_result = compile_func(self, token)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/alprostov/PycharmProjects/sakhlis/venv3/lib/python3.11/site-packages/django/template/defaulttags.py", line 953, in do_if
    nodelist = parser.parse(("elif", "else", "endif"))
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/alprostov/PycharmProjects/sakhlis/venv3/lib/python3.11/site-packages/django/template/base.py", line 513, in parse
    raise self.error(token, e)
  File "/home/alprostov/PycharmProjects/sakhlis/venv3/lib/python3.11/site-packages/django/template/base.py", line 511, in parse
    compiled_result = compile_func(self, token)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/alprostov/PycharmProjects/sakhlis/venv3/lib/python3.11/site-packages/django/template/defaulttags.py", line 953, in do_if
    nodelist = parser.parse(("elif", "else", "endif"))
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/alprostov/PycharmProjects/sakhlis/venv3/lib/python3.11/site-packages/django/template/base.py", line 484, in parse
    raise self.error(token, e)
  File "/home/alprostov/PycharmProjects/sakhlis/venv3/lib/python3.11/site-packages/django/template/base.py", line 482, in parse
    filter_expression = self.compile_filter(token.contents)
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/alprostov/PycharmProjects/sakhlis/venv3/lib/python3.11/site-packages/django/template/base.py", line 600, in compile_filter
    return FilterExpression(token, self)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/alprostov/PycharmProjects/sakhlis/venv3/lib/python3.11/site-packages/django/template/base.py", line 698, in __init__
    filter_func = parser.find_filter(filter_name)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/alprostov/PycharmProjects/sakhlis/venv3/lib/python3.11/site-packages/django/template/base.py", line 606, in find_filter
    raise TemplateSyntaxError("Invalid filter: '%s'" % filter_name)
django.template.exceptions.TemplateSyntaxError: Invalid filter: 'url_replace'
06/Jan/2024 22:15:45   ERROR  "GET /ordersearch/?page=15 HTTP/1.1" 500 271682  None
ERROR:django.server:"GET /ordersearch/?page=15 HTTP/1.1" 500 271682
06/Jan/2024 22:21:51   INFO  /home/alprostov/PycharmProjects/sakhlis/sakhlis/web/app_site/templatetags/custom_tags.py changed, reloading.  None
INFO:django.utils.autoreload:/home/alprostov/PycharmProjects/sakhlis/sakhlis/web/app_site/templatetags/custom_tags.py changed, reloading.
06/Jan/2024 22:21:53   INFO  Watching for file changes with StatReloader  None
06/Jan/2024 22:21:54   ERROR  Internal Server Error: /ordersearch/  (<class 'django.template.exceptions.TemplateSyntaxError'>, TemplateSyntaxError("'custom_tags' is not a registered tag library. Must be one of:\nadmin_list\nadmin_modify\nadmin_urls\ncache\ncrispy_forms_field\ncrispy_forms_filters\ncrispy_forms_tags\ncrispy_forms_utils\ncustom_filters\nflatpages\ni18n\nl10n\nlog\nslippers\nstatic\ntz"), <traceback object at 0x7fbd469afc80>)
Traceback (most recent call last):
  File "/home/alprostov/PycharmProjects/sakhlis/venv3/lib/python3.11/site-packages/django/template/defaulttags.py", line 1026, in find_library
    return parser.libraries[name]
           ~~~~~~~~~~~~~~~~^^^^^^
KeyError: 'custom_tags'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/alprostov/PycharmProjects/sakhlis/venv3/lib/python3.11/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/home/alprostov/PycharmProjects/sakhlis/venv3/lib/python3.11/site-packages/django/core/handlers/base.py", line 220, in _get_response
    response = response.render()
               ^^^^^^^^^^^^^^^^^
  File "/home/alprostov/PycharmProjects/sakhlis/venv3/lib/python3.11/site-packages/django/template/response.py", line 111, in render
    self.content = self.rendered_content
                   ^^^^^^^^^^^^^^^^^^^^^
  File "/home/alprostov/PycharmProjects/sakhlis/venv3/lib/python3.11/site-packages/django/template/response.py", line 87, in rendered_content
    template = self.resolve_template(self.template_name)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/alprostov/PycharmProjects/sakhlis/venv3/lib/python3.11/site-packages/django/template/response.py", line 69, in resolve_template
    return select_template(template, using=self.using)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/alprostov/PycharmProjects/sakhlis/venv3/lib/python3.11/site-packages/django/template/loader.py", line 42, in select_template
    return engine.get_template(template_name)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/alprostov/PycharmProjects/sakhlis/venv3/lib/python3.11/site-packages/django/template/backends/django.py", line 33, in get_template
    return Template(self.engine.get_template(template_name), self)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/alprostov/PycharmProjects/sakhlis/venv3/lib/python3.11/site-packages/django/template/engine.py", line 175, in get_template
    template, origin = self.find_template(template_name)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/alprostov/PycharmProjects/sakhlis/venv3/lib/python3.11/site-packages/django/template/engine.py", line 157, in find_template
    template = loader.get_template(name, skip=skip)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/alprostov/PycharmProjects/sakhlis/venv3/lib/python3.11/site-packages/django/template/loaders/cached.py", line 57, in get_template
    template = super().get_template(template_name, skip)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/alprostov/PycharmProjects/sakhlis/venv3/lib/python3.11/site-packages/django/template/loaders/base.py", line 28, in get_template
    return Template(
           ^^^^^^^^^
  File "/home/alprostov/PycharmProjects/sakhlis/venv3/lib/python3.11/site-packages/django/template/base.py", line 154, in __init__
    self.nodelist = self.compile_nodelist()
                    ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/alprostov/PycharmProjects/sakhlis/venv3/lib/python3.11/site-packages/django/template/base.py", line 200, in compile_nodelist
    return parser.parse()
           ^^^^^^^^^^^^^^
  File "/home/alprostov/PycharmProjects/sakhlis/venv3/lib/python3.11/site-packages/django/template/base.py", line 513, in parse
    raise self.error(token, e)
  File "/home/alprostov/PycharmProjects/sakhlis/venv3/lib/python3.11/site-packages/django/template/base.py", line 511, in parse
    compiled_result = compile_func(self, token)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/alprostov/PycharmProjects/sakhlis/venv3/lib/python3.11/site-packages/django/template/loader_tags.py", line 293, in do_extends
    nodelist = parser.parse()
               ^^^^^^^^^^^^^^
  File "/home/alprostov/PycharmProjects/sakhlis/venv3/lib/python3.11/site-packages/django/template/base.py", line 513, in parse
    raise self.error(token, e)
  File "/home/alprostov/PycharmProjects/sakhlis/venv3/lib/python3.11/site-packages/django/template/base.py", line 511, in parse
    compiled_result = compile_func(self, token)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/alprostov/PycharmProjects/sakhlis/venv3/lib/python3.11/site-packages/django/template/defaulttags.py", line 1088, in load
    lib = find_library(parser, name)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/alprostov/PycharmProjects/sakhlis/venv3/lib/python3.11/site-packages/django/template/defaulttags.py", line 1028, in find_library
    raise TemplateSyntaxError(
django.template.exceptions.TemplateSyntaxError: 'custom_tags' is not a registered tag library. Must be one of:
admin_list
admin_modify
admin_urls
cache
crispy_forms_field
crispy_forms_filters
crispy_forms_tags
crispy_forms_utils
custom_filters
flatpages
i18n
l10n
log
slippers
static
tz
ERROR:django.request:Internal Server Error: /ordersearch/
Traceback (most recent call last):
  File "/home/alprostov/PycharmProjects/sakhlis/venv3/lib/python3.11/site-packages/django/template/defaulttags.py", line 1026, in find_library
    return parser.libraries[name]
           ~~~~~~~~~~~~~~~~^^^^^^
KeyError: 'custom_tags'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/alprostov/PycharmProjects/sakhlis/venv3/lib/python3.11/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/home/alprostov/PycharmProjects/sakhlis/venv3/lib/python3.11/site-packages/django/core/handlers/base.py", line 220, in _get_response
    response = response.render()
               ^^^^^^^^^^^^^^^^^
  File "/home/alprostov/PycharmProjects/sakhlis/venv3/lib/python3.11/site-packages/django/template/response.py", line 111, in render
    self.content = self.rendered_content
                   ^^^^^^^^^^^^^^^^^^^^^
  File "/home/alprostov/PycharmProjects/sakhlis/venv3/lib/python3.11/site-packages/django/template/response.py", line 87, in rendered_content
    template = self.resolve_template(self.template_name)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/alprostov/PycharmProjects/sakhlis/venv3/lib/python3.11/site-packages/django/template/response.py", line 69, in resolve_template
    return select_template(template, using=self.using)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/alprostov/PycharmProjects/sakhlis/venv3/lib/python3.11/site-packages/django/template/loader.py", line 42, in select_template
    return engine.get_template(template_name)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/alprostov/PycharmProjects/sakhlis/venv3/lib/python3.11/site-packages/django/template/backends/django.py", line 33, in get_template
    return Template(self.engine.get_template(template_name), self)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/alprostov/PycharmProjects/sakhlis/venv3/lib/python3.11/site-packages/django/template/engine.py", line 175, in get_template
    template, origin = self.find_template(template_name)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/alprostov/PycharmProjects/sakhlis/venv3/lib/python3.11/site-packages/django/template/engine.py", line 157, in find_template
    template = loader.get_template(name, skip=skip)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/alprostov/PycharmProjects/sakhlis/venv3/lib/python3.11/site-packages/django/template/loaders/cached.py", line 57, in get_template
    template = super().get_template(template_name, skip)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/alprostov/PycharmProjects/sakhlis/venv3/lib/python3.11/site-packages/django/template/loaders/base.py", line 28, in get_template
    return Template(
           ^^^^^^^^^
  File "/home/alprostov/PycharmProjects/sakhlis/venv3/lib/python3.11/site-packages/django/template/base.py", line 154, in __init__
    self.nodelist = self.compile_nodelist()
                    ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/alprostov/PycharmProjects/sakhlis/venv3/lib/python3.11/site-packages/django/template/base.py", line 200, in compile_nodelist
    return parser.parse()
           ^^^^^^^^^^^^^^
  File "/home/alprostov/PycharmProjects/sakhlis/venv3/lib/python3.11/site-packages/django/template/base.py", line 513, in parse
    raise self.error(token, e)
  File "/home/alprostov/PycharmProjects/sakhlis/venv3/lib/python3.11/site-packages/django/template/base.py", line 511, in parse
    compiled_result = compile_func(self, token)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/alprostov/PycharmProjects/sakhlis/venv3/lib/python3.11/site-packages/django/template/loader_tags.py", line 293, in do_extends
    nodelist = parser.parse()
               ^^^^^^^^^^^^^^
  File "/home/alprostov/PycharmProjects/sakhlis/venv3/lib/python3.11/site-packages/django/template/base.py", line 513, in parse
    raise self.error(token, e)
  File "/home/alprostov/PycharmProjects/sakhlis/venv3/lib/python3.11/site-packages/django/template/base.py", line 511, in parse
    compiled_result = compile_func(self, token)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/alprostov/PycharmProjects/sakhlis/venv3/lib/python3.11/site-packages/django/template/defaulttags.py", line 1088, in load
    lib = find_library(parser, name)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/alprostov/PycharmProjects/sakhlis/venv3/lib/python3.11/site-packages/django/template/defaulttags.py", line 1028, in find_library
    raise TemplateSyntaxError(
django.template.exceptions.TemplateSyntaxError: 'custom_tags' is not a registered tag library. Must be one of:
admin_list
admin_modify
admin_urls
cache
crispy_forms_field
crispy_forms_filters
crispy_forms_tags
crispy_forms_utils
custom_filters
flatpages
i18n
l10n
log
slippers
static
tz
06/Jan/2024 22:21:54   ERROR  "GET /ordersearch/?page=15 HTTP/1.1" 500 240051  None
ERROR:django.server:"GET /ordersearch/?page=15 HTTP/1.1" 500 240051
06/Jan/2024 22:21:56   ERROR  Internal Server Error: /ordersearch/  (<class 'django.template.exceptions.TemplateSyntaxError'>, TemplateSyntaxError("'custom_tags' is not a registered tag library. Must be one of:\nadmin_list\nadmin_modify\nadmin_urls\ncache\ncrispy_forms_field\ncrispy_forms_filters\ncrispy_forms_tags\ncrispy_forms_utils\ncustom_filters\nflatpages\ni18n\nl10n\nlog\nslippers\nstatic\ntz"), <traceback object at 0x7fbd46643500>)
Traceback (most recent call last):
  File "/home/alprostov/PycharmProjects/sakhlis/venv3/lib/python3.11/site-packages/django/template/defaulttags.py", line 1026, in find_library
    return parser.libraries[name]
           ~~~~~~~~~~~~~~~~^^^^^^
KeyError: 'custom_tags'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/alprostov/PycharmProjects/sakhlis/venv3/lib/python3.11/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/home/alprostov/PycharmProjects/sakhlis/venv3/lib/python3.11/site-packages/django/core/handlers/base.py", line 220, in _get_response
    response = response.render()
               ^^^^^^^^^^^^^^^^^
  File "/home/alprostov/PycharmProjects/sakhlis/venv3/lib/python3.11/site-packages/django/template/response.py", line 111, in render
    self.content = self.rendered_content
                   ^^^^^^^^^^^^^^^^^^^^^
  File "/home/alprostov/PycharmProjects/sakhlis/venv3/lib/python3.11/site-packages/django/template/response.py", line 87, in rendered_content
    template = self.resolve_template(self.template_name)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/alprostov/PycharmProjects/sakhlis/venv3/lib/python3.11/site-packages/django/template/response.py", line 69, in resolve_template
    return select_template(template, using=self.using)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/alprostov/PycharmProjects/sakhlis/venv3/lib/python3.11/site-packages/django/template/loader.py", line 42, in select_template
    return engine.get_template(template_name)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/alprostov/PycharmProjects/sakhlis/venv3/lib/python3.11/site-packages/django/template/backends/django.py", line 33, in get_template
    return Template(self.engine.get_template(template_name), self)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/alprostov/PycharmProjects/sakhlis/venv3/lib/python3.11/site-packages/django/template/engine.py", line 175, in get_template
    template, origin = self.find_template(template_name)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/alprostov/PycharmProjects/sakhlis/venv3/lib/python3.11/site-packages/django/template/engine.py", line 157, in find_template
    template = loader.get_template(name, skip=skip)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/alprostov/PycharmProjects/sakhlis/venv3/lib/python3.11/site-packages/django/template/loaders/cached.py", line 57, in get_template
    template = super().get_template(template_name, skip)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/alprostov/PycharmProjects/sakhlis/venv3/lib/python3.11/site-packages/django/template/loaders/base.py", line 28, in get_template
    return Template(
           ^^^^^^^^^
  File "/home/alprostov/PycharmProjects/sakhlis/venv3/lib/python3.11/site-packages/django/template/base.py", line 154, in __init__
    self.nodelist = self.compile_nodelist()
                    ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/alprostov/PycharmProjects/sakhlis/venv3/lib/python3.11/site-packages/django/template/base.py", line 200, in compile_nodelist
    return parser.parse()
           ^^^^^^^^^^^^^^
  File "/home/alprostov/PycharmProjects/sakhlis/venv3/lib/python3.11/site-packages/django/template/base.py", line 513, in parse
    raise self.error(token, e)
  File "/home/alprostov/PycharmProjects/sakhlis/venv3/lib/python3.11/site-packages/django/template/base.py", line 511, in parse
    compiled_result = compile_func(self, token)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/alprostov/PycharmProjects/sakhlis/venv3/lib/python3.11/site-packages/django/template/loader_tags.py", line 293, in do_extends
    nodelist = parser.parse()
               ^^^^^^^^^^^^^^
  File "/home/alprostov/PycharmProjects/sakhlis/venv3/lib/python3.11/site-packages/django/template/base.py", line 513, in parse
    raise self.error(token, e)
  File "/home/alprostov/PycharmProjects/sakhlis/venv3/lib/python3.11/site-packages/django/template/base.py", line 511, in parse
    compiled_result = compile_func(self, token)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/alprostov/PycharmProjects/sakhlis/venv3/lib/python3.11/site-packages/django/template/defaulttags.py", line 1088, in load
    lib = find_library(parser, name)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/alprostov/PycharmProjects/sakhlis/venv3/lib/python3.11/site-packages/django/template/defaulttags.py", line 1028, in find_library
    raise TemplateSyntaxError(
django.template.exceptions.TemplateSyntaxError: 'custom_tags' is not a registered tag library. Must be one of:
admin_list
admin_modify
admin_urls
cache
crispy_forms_field
crispy_forms_filters
crispy_forms_tags
crispy_forms_utils
custom_filters
flatpages
i18n
l10n
log
slippers
static
tz
ERROR:django.request:Internal Server Error: /ordersearch/
Traceback (most recent call last):
  File "/home/alprostov/PycharmProjects/sakhlis/venv3/lib/python3.11/site-packages/django/template/defaulttags.py", line 1026, in find_library
    return parser.libraries[name]
           ~~~~~~~~~~~~~~~~^^^^^^
KeyError: 'custom_tags'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/alprostov/PycharmProjects/sakhlis/venv3/lib/python3.11/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/home/alprostov/PycharmProjects/sakhlis/venv3/lib/python3.11/site-packages/django/core/handlers/base.py", line 220, in _get_response
    response = response.render()
               ^^^^^^^^^^^^^^^^^
  File "/home/alprostov/PycharmProjects/sakhlis/venv3/lib/python3.11/site-packages/django/template/response.py", line 111, in render
    self.content = self.rendered_content
                   ^^^^^^^^^^^^^^^^^^^^^
  File "/home/alprostov/PycharmProjects/sakhlis/venv3/lib/python3.11/site-packages/django/template/response.py", line 87, in rendered_content
    template = self.resolve_template(self.template_name)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/alprostov/PycharmProjects/sakhlis/venv3/lib/python3.11/site-packages/django/template/response.py", line 69, in resolve_template
    return select_template(template, using=self.using)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/alprostov/PycharmProjects/sakhlis/venv3/lib/python3.11/site-packages/django/template/loader.py", line 42, in select_template
    return engine.get_template(template_name)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/alprostov/PycharmProjects/sakhlis/venv3/lib/python3.11/site-packages/django/template/backends/django.py", line 33, in get_template
    return Template(self.engine.get_template(template_name), self)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/alprostov/PycharmProjects/sakhlis/venv3/lib/python3.11/site-packages/django/template/engine.py", line 175, in get_template
    template, origin = self.find_template(template_name)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/alprostov/PycharmProjects/sakhlis/venv3/lib/python3.11/site-packages/django/template/engine.py", line 157, in find_template
    template = loader.get_template(name, skip=skip)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/alprostov/PycharmProjects/sakhlis/venv3/lib/python3.11/site-packages/django/template/loaders/cached.py", line 57, in get_template
    template = super().get_template(template_name, skip)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/alprostov/PycharmProjects/sakhlis/venv3/lib/python3.11/site-packages/django/template/loaders/base.py", line 28, in get_template
    return Template(
           ^^^^^^^^^
  File "/home/alprostov/PycharmProjects/sakhlis/venv3/lib/python3.11/site-packages/django/template/base.py", line 154, in __init__
    self.nodelist = self.compile_nodelist()
                    ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/alprostov/PycharmProjects/sakhlis/venv3/lib/python3.11/site-packages/django/template/base.py", line 200, in compile_nodelist
    return parser.parse()
           ^^^^^^^^^^^^^^
  File "/home/alprostov/PycharmProjects/sakhlis/venv3/lib/python3.11/site-packages/django/template/base.py", line 513, in parse
    raise self.error(token, e)
  File "/home/alprostov/PycharmProjects/sakhlis/venv3/lib/python3.11/site-packages/django/template/base.py", line 511, in parse
    compiled_result = compile_func(self, token)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/alprostov/PycharmProjects/sakhlis/venv3/lib/python3.11/site-packages/django/template/loader_tags.py", line 293, in do_extends
    nodelist = parser.parse()
               ^^^^^^^^^^^^^^
  File "/home/alprostov/PycharmProjects/sakhlis/venv3/lib/python3.11/site-packages/django/template/base.py", line 513, in parse
    raise self.error(token, e)
  File "/home/alprostov/PycharmProjects/sakhlis/venv3/lib/python3.11/site-packages/django/template/base.py", line 511, in parse
    compiled_result = compile_func(self, token)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/alprostov/PycharmProjects/sakhlis/venv3/lib/python3.11/site-packages/django/template/defaulttags.py", line 1088, in load
    lib = find_library(parser, name)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/alprostov/PycharmProjects/sakhlis/venv3/lib/python3.11/site-packages/django/template/defaulttags.py", line 1028, in find_library
    raise TemplateSyntaxError(
django.template.exceptions.TemplateSyntaxError: 'custom_tags' is not a registered tag library. Must be one of:
admin_list
admin_modify
admin_urls
cache
crispy_forms_field
crispy_forms_filters
crispy_forms_tags
crispy_forms_utils
custom_filters
flatpages
i18n
l10n
log
slippers
static
tz
06/Jan/2024 22:21:56   ERROR  "GET /ordersearch/?page=15 HTTP/1.1" 500 240047  None
ERROR:django.server:"GET /ordersearch/?page=15 HTTP/1.1" 500 240047
06/Jan/2024 22:22:00   ERROR  Internal Server Error: /ordersearch/  (<class 'django.template.exceptions.TemplateSyntaxError'>, TemplateSyntaxError("'custom_tags' is not a registered tag library. Must be one of:\nadmin_list\nadmin_modify\nadmin_urls\ncache\ncrispy_forms_field\ncrispy_forms_filters\ncrispy_forms_tags\ncrispy_forms_utils\ncustom_filters\nflatpages\ni18n\nl10n\nlog\nslippers\nstatic\ntz"), <traceback object at 0x7fbd466f3f00>)
Traceback (most recent call last):
  File "/home/alprostov/PycharmProjects/sakhlis/venv3/lib/python3.11/site-packages/django/template/defaulttags.py", line 1026, in find_library
    return parser.libraries[name]
           ~~~~~~~~~~~~~~~~^^^^^^
KeyError: 'custom_tags'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/alprostov/PycharmProjects/sakhlis/venv3/lib/python3.11/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/home/alprostov/PycharmProjects/sakhlis/venv3/lib/python3.11/site-packages/django/core/handlers/base.py", line 220, in _get_response
    response = response.render()
               ^^^^^^^^^^^^^^^^^
  File "/home/alprostov/PycharmProjects/sakhlis/venv3/lib/python3.11/site-packages/django/template/response.py", line 111, in render
    self.content = self.rendered_content
                   ^^^^^^^^^^^^^^^^^^^^^
  File "/home/alprostov/PycharmProjects/sakhlis/venv3/lib/python3.11/site-packages/django/template/response.py", line 87, in rendered_content
    template = self.resolve_template(self.template_name)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/alprostov/PycharmProjects/sakhlis/venv3/lib/python3.11/site-packages/django/template/response.py", line 69, in resolve_template
    return select_template(template, using=self.using)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/alprostov/PycharmProjects/sakhlis/venv3/lib/python3.11/site-packages/django/template/loader.py", line 42, in select_template
    return engine.get_template(template_name)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/alprostov/PycharmProjects/sakhlis/venv3/lib/python3.11/site-packages/django/template/backends/django.py", line 33, in get_template
    return Template(self.engine.get_template(template_name), self)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/alprostov/PycharmProjects/sakhlis/venv3/lib/python3.11/site-packages/django/template/engine.py", line 175, in get_template
    template, origin = self.find_template(template_name)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/alprostov/PycharmProjects/sakhlis/venv3/lib/python3.11/site-packages/django/template/engine.py", line 157, in find_template
    template = loader.get_template(name, skip=skip)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/alprostov/PycharmProjects/sakhlis/venv3/lib/python3.11/site-packages/django/template/loaders/cached.py", line 57, in get_template
    template = super().get_template(template_name, skip)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/alprostov/PycharmProjects/sakhlis/venv3/lib/python3.11/site-packages/django/template/loaders/base.py", line 28, in get_template
    return Template(
           ^^^^^^^^^
  File "/home/alprostov/PycharmProjects/sakhlis/venv3/lib/python3.11/site-packages/django/template/base.py", line 154, in __init__
    self.nodelist = self.compile_nodelist()
                    ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/alprostov/PycharmProjects/sakhlis/venv3/lib/python3.11/site-packages/django/template/base.py", line 200, in compile_nodelist
    return parser.parse()
           ^^^^^^^^^^^^^^
  File "/home/alprostov/PycharmProjects/sakhlis/venv3/lib/python3.11/site-packages/django/template/base.py", line 513, in parse
    raise self.error(token, e)
  File "/home/alprostov/PycharmProjects/sakhlis/venv3/lib/python3.11/site-packages/django/template/base.py", line 511, in parse
    compiled_result = compile_func(self, token)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/alprostov/PycharmProjects/sakhlis/venv3/lib/python3.11/site-packages/django/template/loader_tags.py", line 293, in do_extends
    nodelist = parser.parse()
               ^^^^^^^^^^^^^^
  File "/home/alprostov/PycharmProjects/sakhlis/venv3/lib/python3.11/site-packages/django/template/base.py", line 513, in parse
    raise self.error(token, e)
  File "/home/alprostov/PycharmProjects/sakhlis/venv3/lib/python3.11/site-packages/django/template/base.py", line 511, in parse
    compiled_result = compile_func(self, token)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/alprostov/PycharmProjects/sakhlis/venv3/lib/python3.11/site-packages/django/template/defaulttags.py", line 1088, in load
    lib = find_library(parser, name)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/alprostov/PycharmProjects/sakhlis/venv3/lib/python3.11/site-packages/django/template/defaulttags.py", line 1028, in find_library
    raise TemplateSyntaxError(
django.template.exceptions.TemplateSyntaxError: 'custom_tags' is not a registered tag library. Must be one of:
admin_list
admin_modify
admin_urls
cache
crispy_forms_field
crispy_forms_filters
crispy_forms_tags
crispy_forms_utils
custom_filters
flatpages
i18n
l10n
log
slippers
static
tz
ERROR:django.request:Internal Server Error: /ordersearch/
Traceback (most recent call last):
  File "/home/alprostov/PycharmProjects/sakhlis/venv3/lib/python3.11/site-packages/django/template/defaulttags.py", line 1026, in find_library
    return parser.libraries[name]
           ~~~~~~~~~~~~~~~~^^^^^^
KeyError: 'custom_tags'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/alprostov/PycharmProjects/sakhlis/venv3/lib/python3.11/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/home/alprostov/PycharmProjects/sakhlis/venv3/lib/python3.11/site-packages/django/core/handlers/base.py", line 220, in _get_response
    response = response.render()
               ^^^^^^^^^^^^^^^^^
  File "/home/alprostov/PycharmProjects/sakhlis/venv3/lib/python3.11/site-packages/django/template/response.py", line 111, in render
    self.content = self.rendered_content
                   ^^^^^^^^^^^^^^^^^^^^^
  File "/home/alprostov/PycharmProjects/sakhlis/venv3/lib/python3.11/site-packages/django/template/response.py", line 87, in rendered_content
    template = self.resolve_template(self.template_name)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/alprostov/PycharmProjects/sakhlis/venv3/lib/python3.11/site-packages/django/template/response.py", line 69, in resolve_template
    return select_template(template, using=self.using)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/alprostov/PycharmProjects/sakhlis/venv3/lib/python3.11/site-packages/django/template/loader.py", line 42, in select_template
    return engine.get_template(template_name)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/alprostov/PycharmProjects/sakhlis/venv3/lib/python3.11/site-packages/django/template/backends/django.py", line 33, in get_template
    return Template(self.engine.get_template(template_name), self)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/alprostov/PycharmProjects/sakhlis/venv3/lib/python3.11/site-packages/django/template/engine.py", line 175, in get_template
    template, origin = self.find_template(template_name)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/alprostov/PycharmProjects/sakhlis/venv3/lib/python3.11/site-packages/django/template/engine.py", line 157, in find_template
    template = loader.get_template(name, skip=skip)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/alprostov/PycharmProjects/sakhlis/venv3/lib/python3.11/site-packages/django/template/loaders/cached.py", line 57, in get_template
    template = super().get_template(template_name, skip)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/alprostov/PycharmProjects/sakhlis/venv3/lib/python3.11/site-packages/django/template/loaders/base.py", line 28, in get_template
    return Template(
           ^^^^^^^^^
  File "/home/alprostov/PycharmProjects/sakhlis/venv3/lib/python3.11/site-packages/django/template/base.py", line 154, in __init__
    self.nodelist = self.compile_nodelist()
                    ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/alprostov/PycharmProjects/sakhlis/venv3/lib/python3.11/site-packages/django/template/base.py", line 200, in compile_nodelist
    return parser.parse()
           ^^^^^^^^^^^^^^
  File "/home/alprostov/PycharmProjects/sakhlis/venv3/lib/python3.11/site-packages/django/template/base.py", line 513, in parse
    raise self.error(token, e)
  File "/home/alprostov/PycharmProjects/sakhlis/venv3/lib/python3.11/site-packages/django/template/base.py", line 511, in parse
    compiled_result = compile_func(self, token)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/alprostov/PycharmProjects/sakhlis/venv3/lib/python3.11/site-packages/django/template/loader_tags.py", line 293, in do_extends
    nodelist = parser.parse()
               ^^^^^^^^^^^^^^
  File "/home/alprostov/PycharmProjects/sakhlis/venv3/lib/python3.11/site-packages/django/template/base.py", line 513, in parse
    raise self.error(token, e)
  File "/home/alprostov/PycharmProjects/sakhlis/venv3/lib/python3.11/site-packages/django/template/base.py", line 511, in parse
    compiled_result = compile_func(self, token)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/alprostov/PycharmProjects/sakhlis/venv3/lib/python3.11/site-packages/django/template/defaulttags.py", line 1088, in load
    lib = find_library(parser, name)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/alprostov/PycharmProjects/sakhlis/venv3/lib/python3.11/site-packages/django/template/defaulttags.py", line 1028, in find_library
    raise TemplateSyntaxError(
django.template.exceptions.TemplateSyntaxError: 'custom_tags' is not a registered tag library. Must be one of:
admin_list
admin_modify
admin_urls
cache
crispy_forms_field
crispy_forms_filters
crispy_forms_tags
crispy_forms_utils
custom_filters
flatpages
i18n
l10n
log
slippers
static
tz
06/Jan/2024 22:22:00   ERROR  "GET /ordersearch/?page=15 HTTP/1.1" 500 240047  None
ERROR:django.server:"GET /ordersearch/?page=15 HTTP/1.1" 500 240047
06/Jan/2024 22:22:25   ERROR  Internal Server Error: /ordersearch/  (<class 'django.template.exceptions.TemplateSyntaxError'>, TemplateSyntaxError("'custom_tags' is not a registered tag library. Must be one of:\nadmin_list\nadmin_modify\nadmin_urls\ncache\ncrispy_forms_field\ncrispy_forms_filters\ncrispy_forms_tags\ncrispy_forms_utils\ncustom_filters\nflatpages\ni18n\nl10n\nlog\nslippers\nstatic\ntz"), <traceback object at 0x7fbd46591f40>)
Traceback (most recent call last):
  File "/home/alprostov/PycharmProjects/sakhlis/venv3/lib/python3.11/site-packages/django/template/defaulttags.py", line 1026, in find_library
    return parser.libraries[name]
           ~~~~~~~~~~~~~~~~^^^^^^
KeyError: 'custom_tags'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/alprostov/PycharmProjects/sakhlis/venv3/lib/python3.11/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/home/alprostov/PycharmProjects/sakhlis/venv3/lib/python3.11/site-packages/django/core/handlers/base.py", line 220, in _get_response
    response = response.render()
               ^^^^^^^^^^^^^^^^^
  File "/home/alprostov/PycharmProjects/sakhlis/venv3/lib/python3.11/site-packages/django/template/response.py", line 111, in render
    self.content = self.rendered_content
                   ^^^^^^^^^^^^^^^^^^^^^
  File "/home/alprostov/PycharmProjects/sakhlis/venv3/lib/python3.11/site-packages/django/template/response.py", line 87, in rendered_content
    template = self.resolve_template(self.template_name)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/alprostov/PycharmProjects/sakhlis/venv3/lib/python3.11/site-packages/django/template/response.py", line 69, in resolve_template
    return select_template(template, using=self.using)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/alprostov/PycharmProjects/sakhlis/venv3/lib/python3.11/site-packages/django/template/loader.py", line 42, in select_template
    return engine.get_template(template_name)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/alprostov/PycharmProjects/sakhlis/venv3/lib/python3.11/site-packages/django/template/backends/django.py", line 33, in get_template
    return Template(self.engine.get_template(template_name), self)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/alprostov/PycharmProjects/sakhlis/venv3/lib/python3.11/site-packages/django/template/engine.py", line 175, in get_template
    template, origin = self.find_template(template_name)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/alprostov/PycharmProjects/sakhlis/venv3/lib/python3.11/site-packages/django/template/engine.py", line 157, in find_template
    template = loader.get_template(name, skip=skip)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/alprostov/PycharmProjects/sakhlis/venv3/lib/python3.11/site-packages/django/template/loaders/cached.py", line 57, in get_template
    template = super().get_template(template_name, skip)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/alprostov/PycharmProjects/sakhlis/venv3/lib/python3.11/site-packages/django/template/loaders/base.py", line 28, in get_template
    return Template(
           ^^^^^^^^^
  File "/home/alprostov/PycharmProjects/sakhlis/venv3/lib/python3.11/site-packages/django/template/base.py", line 154, in __init__
    self.nodelist = self.compile_nodelist()
                    ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/alprostov/PycharmProjects/sakhlis/venv3/lib/python3.11/site-packages/django/template/base.py", line 200, in compile_nodelist
    return parser.parse()
           ^^^^^^^^^^^^^^
  File "/home/alprostov/PycharmProjects/sakhlis/venv3/lib/python3.11/site-packages/django/template/base.py", line 513, in parse
    raise self.error(token, e)
  File "/home/alprostov/PycharmProjects/sakhlis/venv3/lib/python3.11/site-packages/django/template/base.py", line 511, in parse
    compiled_result = compile_func(self, token)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/alprostov/PycharmProjects/sakhlis/venv3/lib/python3.11/site-packages/django/template/loader_tags.py", line 293, in do_extends
    nodelist = parser.parse()
               ^^^^^^^^^^^^^^
  File "/home/alprostov/PycharmProjects/sakhlis/venv3/lib/python3.11/site-packages/django/template/base.py", line 513, in parse
    raise self.error(token, e)
  File "/home/alprostov/PycharmProjects/sakhlis/venv3/lib/python3.11/site-packages/django/template/base.py", line 511, in parse
    compiled_result = compile_func(self, token)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/alprostov/PycharmProjects/sakhlis/venv3/lib/python3.11/site-packages/django/template/defaulttags.py", line 1088, in load
    lib = find_library(parser, name)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/alprostov/PycharmProjects/sakhlis/venv3/lib/python3.11/site-packages/django/template/defaulttags.py", line 1028, in find_library
    raise TemplateSyntaxError(
django.template.exceptions.TemplateSyntaxError: 'custom_tags' is not a registered tag library. Must be one of:
admin_list
admin_modify
admin_urls
cache
crispy_forms_field
crispy_forms_filters
crispy_forms_tags
crispy_forms_utils
custom_filters
flatpages
i18n
l10n
log
slippers
static
tz
ERROR:django.request:Internal Server Error: /ordersearch/
Traceback (most recent call last):
  File "/home/alprostov/PycharmProjects/sakhlis/venv3/lib/python3.11/site-packages/django/template/defaulttags.py", line 1026, in find_library
    return parser.libraries[name]
           ~~~~~~~~~~~~~~~~^^^^^^
KeyError: 'custom_tags'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/alprostov/PycharmProjects/sakhlis/venv3/lib/python3.11/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/home/alprostov/PycharmProjects/sakhlis/venv3/lib/python3.11/site-packages/django/core/handlers/base.py", line 220, in _get_response
    response = response.render()
               ^^^^^^^^^^^^^^^^^
  File "/home/alprostov/PycharmProjects/sakhlis/venv3/lib/python3.11/site-packages/django/template/response.py", line 111, in render
    self.content = self.rendered_content
                   ^^^^^^^^^^^^^^^^^^^^^
  File "/home/alprostov/PycharmProjects/sakhlis/venv3/lib/python3.11/site-packages/django/template/response.py", line 87, in rendered_content
    template = self.resolve_template(self.template_name)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/alprostov/PycharmProjects/sakhlis/venv3/lib/python3.11/site-packages/django/template/response.py", line 69, in resolve_template
    return select_template(template, using=self.using)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/alprostov/PycharmProjects/sakhlis/venv3/lib/python3.11/site-packages/django/template/loader.py", line 42, in select_template
    return engine.get_template(template_name)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/alprostov/PycharmProjects/sakhlis/venv3/lib/python3.11/site-packages/django/template/backends/django.py", line 33, in get_template
    return Template(self.engine.get_template(template_name), self)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/alprostov/PycharmProjects/sakhlis/venv3/lib/python3.11/site-packages/django/template/engine.py", line 175, in get_template
    template, origin = self.find_template(template_name)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/alprostov/PycharmProjects/sakhlis/venv3/lib/python3.11/site-packages/django/template/engine.py", line 157, in find_template
    template = loader.get_template(name, skip=skip)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/alprostov/PycharmProjects/sakhlis/venv3/lib/python3.11/site-packages/django/template/loaders/cached.py", line 57, in get_template
    template = super().get_template(template_name, skip)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/alprostov/PycharmProjects/sakhlis/venv3/lib/python3.11/site-packages/django/template/loaders/base.py", line 28, in get_template
    return Template(
           ^^^^^^^^^
  File "/home/alprostov/PycharmProjects/sakhlis/venv3/lib/python3.11/site-packages/django/template/base.py", line 154, in __init__
    self.nodelist = self.compile_nodelist()
                    ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/alprostov/PycharmProjects/sakhlis/venv3/lib/python3.11/site-packages/django/template/base.py", line 200, in compile_nodelist
    return parser.parse()
           ^^^^^^^^^^^^^^
  File "/home/alprostov/PycharmProjects/sakhlis/venv3/lib/python3.11/site-packages/django/template/base.py", line 513, in parse
    raise self.error(token, e)
  File "/home/alprostov/PycharmProjects/sakhlis/venv3/lib/python3.11/site-packages/django/template/base.py", line 511, in parse
    compiled_result = compile_func(self, token)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/alprostov/PycharmProjects/sakhlis/venv3/lib/python3.11/site-packages/django/template/loader_tags.py", line 293, in do_extends
    nodelist = parser.parse()
               ^^^^^^^^^^^^^^
  File "/home/alprostov/PycharmProjects/sakhlis/venv3/lib/python3.11/site-packages/django/template/base.py", line 513, in parse
    raise self.error(token, e)
  File "/home/alprostov/PycharmProjects/sakhlis/venv3/lib/python3.11/site-packages/django/template/base.py", line 511, in parse
    compiled_result = compile_func(self, token)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/alprostov/PycharmProjects/sakhlis/venv3/lib/python3.11/site-packages/django/template/defaulttags.py", line 1088, in load
    lib = find_library(parser, name)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/alprostov/PycharmProjects/sakhlis/venv3/lib/python3.11/site-packages/django/template/defaulttags.py", line 1028, in find_library
    raise TemplateSyntaxError(
django.template.exceptions.TemplateSyntaxError: 'custom_tags' is not a registered tag library. Must be one of:
admin_list
admin_modify
admin_urls
cache
crispy_forms_field
crispy_forms_filters
crispy_forms_tags
crispy_forms_utils
custom_filters
flatpages
i18n
l10n
log
slippers
static
tz
06/Jan/2024 22:22:25   ERROR  "GET /ordersearch/?page=15 HTTP/1.1" 500 240067  None
ERROR:django.server:"GET /ordersearch/?page=15 HTTP/1.1" 500 240067
06/Jan/2024 22:22:41   INFO  /home/alprostov/PycharmProjects/sakhlis/sakhlis/web/app_site/templatetags/custom_filters.py changed, reloading.  None
INFO:django.utils.autoreload:/home/alprostov/PycharmProjects/sakhlis/sakhlis/web/app_site/templatetags/custom_filters.py changed, reloading.
06/Jan/2024 22:22:43   INFO  Watching for file changes with StatReloader  None
06/Jan/2024 22:22:45   INFO  /home/alprostov/PycharmProjects/sakhlis/sakhlis/web/app_site/templatetags/custom_tags.py changed, reloading.  None
INFO:django.utils.autoreload:/home/alprostov/PycharmProjects/sakhlis/sakhlis/web/app_site/templatetags/custom_tags.py changed, reloading.
06/Jan/2024 22:22:47   INFO  Watching for file changes with StatReloader  None
06/Jan/2024 22:23:27   INFO  "GET /ordersearch/?page=15 HTTP/1.1" 200 41766  None
INFO:django.server:"GET /ordersearch/?page=15 HTTP/1.1" 200 41766
06/Jan/2024 22:23:27   WARNING  "GET /static/js/counter.js HTTP/1.1" 404 1798  None
WARNING:django.server:"GET /static/js/counter.js HTTP/1.1" 404 1798
06/Jan/2024 22:23:29   INFO  "GET /list_order?work_status=RCV HTTP/1.1" 200 30211  None
INFO:django.server:"GET /list_order?work_status=RCV HTTP/1.1" 200 30211
06/Jan/2024 22:23:29   WARNING  "GET /static/js/counter.js HTTP/1.1" 404 1798  None
WARNING:django.server:"GET /static/js/counter.js HTTP/1.1" 404 1798
06/Jan/2024 22:23:30   INFO  "GET /list_order?work_status=END HTTP/1.1" 200 53766  None
INFO:django.server:"GET /list_order?work_status=END HTTP/1.1" 200 53766
06/Jan/2024 22:23:30   WARNING  "GET /static/js/counter.js HTTP/1.1" 404 1798  None
WARNING:django.server:"GET /static/js/counter.js HTTP/1.1" 404 1798
06/Jan/2024 22:23:33   INFO  "GET /ordersearch/ HTTP/1.1" 200 55716  None
INFO:django.server:"GET /ordersearch/ HTTP/1.1" 200 55716
06/Jan/2024 22:23:33   WARNING  "GET /static/js/counter.js HTTP/1.1" 404 1798  None
WARNING:django.server:"GET /static/js/counter.js HTTP/1.1" 404 1798
06/Jan/2024 22:23:51   INFO  "GET /ordersearch/?time_in_sence=&time_in_until=&order_status=BEG&repairer_id=51&customer_name=&customer_phone=&customer_telegram=&address_city=&adress_street_app=&address_num= HTTP/1.1" 200 20548  None
INFO:django.server:"GET /ordersearch/?time_in_sence=&time_in_until=&order_status=BEG&repairer_id=51&customer_name=&customer_phone=&customer_telegram=&address_city=&adress_street_app=&address_num= HTTP/1.1" 200 20548
06/Jan/2024 22:23:51   WARNING  "GET /static/js/counter.js HTTP/1.1" 404 1798  None
WARNING:django.server:"GET /static/js/counter.js HTTP/1.1" 404 1798
06/Jan/2024 22:23:56   INFO  "GET /ordersearch/?time_in_sence=&time_in_until=&order_status=RCV&repairer_id=51&customer_name=&customer_phone=&customer_telegram=&address_city=&adress_street_app=&address_num= HTTP/1.1" 200 30094  None
INFO:django.server:"GET /ordersearch/?time_in_sence=&time_in_until=&order_status=RCV&repairer_id=51&customer_name=&customer_phone=&customer_telegram=&address_city=&adress_street_app=&address_num= HTTP/1.1" 200 30094
06/Jan/2024 22:23:56   WARNING  "GET /static/js/counter.js HTTP/1.1" 404 1798  None
WARNING:django.server:"GET /static/js/counter.js HTTP/1.1" 404 1798
06/Jan/2024 22:24:03   INFO  "GET /list_order?work_status=RCV HTTP/1.1" 200 30211  None
INFO:django.server:"GET /list_order?work_status=RCV HTTP/1.1" 200 30211
06/Jan/2024 22:24:03   WARNING  "GET /static/js/counter.js HTTP/1.1" 404 1798  None
WARNING:django.server:"GET /static/js/counter.js HTTP/1.1" 404 1798
06/Jan/2024 22:24:05   INFO  "GET /list_order?work_status=END HTTP/1.1" 200 53766  None
INFO:django.server:"GET /list_order?work_status=END HTTP/1.1" 200 53766
06/Jan/2024 22:24:05   WARNING  "GET /static/js/counter.js HTTP/1.1" 404 1798  None
WARNING:django.server:"GET /static/js/counter.js HTTP/1.1" 404 1798
06/Jan/2024 22:24:07   INFO  "GET /stat/ HTTP/1.1" 200 190352  None
INFO:django.server:"GET /stat/ HTTP/1.1" 200 190352
06/Jan/2024 22:24:07   WARNING  "GET /static/js/counter.js HTTP/1.1" 404 1798  None
WARNING:django.server:"GET /static/js/counter.js HTTP/1.1" 404 1798
