29/Jan/2024 19:27:50   ERROR  Invalid HTTP_HOST header: '127.0.0.1:8000'. You may need to add '127.0.0.1' to ALLOWED_HOSTS.  (<class 'django.core.exceptions.DisallowedHost'>, DisallowedHost("Invalid HTTP_HOST header: '127.0.0.1:8000'. You may need to add '127.0.0.1' to ALLOWED_HOSTS."), <traceback object at 0x7fcf49543b80>)
Traceback (most recent call last):
  File "/home/alprostov/PycharmProjects/sakhlis/venv3/lib/python3.11/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/home/alprostov/PycharmProjects/sakhlis/venv3/lib/python3.11/site-packages/django/utils/deprecation.py", line 133, in __call__
    response = self.process_request(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/alprostov/PycharmProjects/sakhlis/venv3/lib/python3.11/site-packages/django/middleware/common.py", line 48, in process_request
    host = request.get_host()
           ^^^^^^^^^^^^^^^^^^
  File "/home/alprostov/PycharmProjects/sakhlis/venv3/lib/python3.11/site-packages/django/http/request.py", line 167, in get_host
    raise DisallowedHost(msg)
django.core.exceptions.DisallowedHost: Invalid HTTP_HOST header: '127.0.0.1:8000'. You may need to add '127.0.0.1' to ALLOWED_HOSTS.
29/Jan/2024 19:27:50   WARNING  Bad Request: /  None
WARNING:django.request:Bad Request: /
30/Jan/2024 07:13:01   WARNING  "GET /static/js/counter.js HTTP/1.1" 404 1798  None
WARNING:django.server:"GET /static/js/counter.js HTTP/1.1" 404 1798
30/Jan/2024 07:13:01   WARNING  Not Found: /favicon.ico  None
WARNING:django.request:Not Found: /favicon.ico
30/Jan/2024 07:13:01   WARNING  "GET /favicon.ico HTTP/1.1" 404 16307  None
WARNING:django.server:"GET /favicon.ico HTTP/1.1" 404 16307
30/Jan/2024 07:13:03   WARNING  "GET /static/js/counter.js HTTP/1.1" 404 1798  None
WARNING:django.server:"GET /static/js/counter.js HTTP/1.1" 404 1798
30/Jan/2024 07:13:06   WARNING  "GET /static/js/counter.js HTTP/1.1" 404 1798  None
WARNING:django.server:"GET /static/js/counter.js HTTP/1.1" 404 1798
30/Jan/2024 07:14:03   ERROR  Invalid HTTP_HOST header: '127.0.0.1:8000'. You may need to add '127.0.0.1' to ALLOWED_HOSTS.  (<class 'django.core.exceptions.DisallowedHost'>, DisallowedHost("Invalid HTTP_HOST header: '127.0.0.1:8000'. You may need to add '127.0.0.1' to ALLOWED_HOSTS."), <traceback object at 0x7fbfa4130b00>)
Traceback (most recent call last):
  File "/home/alprostov/PycharmProjects/sakhlis/venv3/lib/python3.11/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/home/alprostov/PycharmProjects/sakhlis/venv3/lib/python3.11/site-packages/django/utils/deprecation.py", line 133, in __call__
    response = self.process_request(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/alprostov/PycharmProjects/sakhlis/venv3/lib/python3.11/site-packages/django/middleware/common.py", line 48, in process_request
    host = request.get_host()
           ^^^^^^^^^^^^^^^^^^
  File "/home/alprostov/PycharmProjects/sakhlis/venv3/lib/python3.11/site-packages/django/http/request.py", line 167, in get_host
    raise DisallowedHost(msg)
django.core.exceptions.DisallowedHost: Invalid HTTP_HOST header: '127.0.0.1:8000'. You may need to add '127.0.0.1' to ALLOWED_HOSTS.
30/Jan/2024 07:14:03   WARNING  Bad Request: /  None
WARNING:django.request:Bad Request: /
30/Jan/2024 07:14:27   ERROR  Invalid HTTP_HOST header: '127.0.0.1:8000'. You may need to add '127.0.0.1' to ALLOWED_HOSTS.  (<class 'django.core.exceptions.DisallowedHost'>, DisallowedHost("Invalid HTTP_HOST header: '127.0.0.1:8000'. You may need to add '127.0.0.1' to ALLOWED_HOSTS."), <traceback object at 0x7f1a8ec91680>)
Traceback (most recent call last):
  File "/home/alprostov/PycharmProjects/sakhlis/venv3/lib/python3.11/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/home/alprostov/PycharmProjects/sakhlis/venv3/lib/python3.11/site-packages/django/utils/deprecation.py", line 133, in __call__
    response = self.process_request(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/alprostov/PycharmProjects/sakhlis/venv3/lib/python3.11/site-packages/django/middleware/common.py", line 48, in process_request
    host = request.get_host()
           ^^^^^^^^^^^^^^^^^^
  File "/home/alprostov/PycharmProjects/sakhlis/venv3/lib/python3.11/site-packages/django/http/request.py", line 167, in get_host
    raise DisallowedHost(msg)
django.core.exceptions.DisallowedHost: Invalid HTTP_HOST header: '127.0.0.1:8000'. You may need to add '127.0.0.1' to ALLOWED_HOSTS.
30/Jan/2024 07:14:27   WARNING  Bad Request: /  None
WARNING:django.request:Bad Request: /
30/Jan/2024 07:14:32   ERROR  Invalid HTTP_HOST header: '127.0.0.1:8000'. You may need to add '127.0.0.1' to ALLOWED_HOSTS.  (<class 'django.core.exceptions.DisallowedHost'>, DisallowedHost("Invalid HTTP_HOST header: '127.0.0.1:8000'. You may need to add '127.0.0.1' to ALLOWED_HOSTS."), <traceback object at 0x7f1a8eca46c0>)
Traceback (most recent call last):
  File "/home/alprostov/PycharmProjects/sakhlis/venv3/lib/python3.11/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/home/alprostov/PycharmProjects/sakhlis/venv3/lib/python3.11/site-packages/django/utils/deprecation.py", line 133, in __call__
    response = self.process_request(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/alprostov/PycharmProjects/sakhlis/venv3/lib/python3.11/site-packages/django/middleware/common.py", line 48, in process_request
    host = request.get_host()
           ^^^^^^^^^^^^^^^^^^
  File "/home/alprostov/PycharmProjects/sakhlis/venv3/lib/python3.11/site-packages/django/http/request.py", line 167, in get_host
    raise DisallowedHost(msg)
django.core.exceptions.DisallowedHost: Invalid HTTP_HOST header: '127.0.0.1:8000'. You may need to add '127.0.0.1' to ALLOWED_HOSTS.
30/Jan/2024 07:14:32   WARNING  Bad Request: /  None
WARNING:django.request:Bad Request: /
30/Jan/2024 07:17:52   WARNING  Not Found: /static/images/whatsapp.png  None
WARNING:django.request:Not Found: /static/images/whatsapp.png
30/Jan/2024 07:17:52   WARNING  Not Found: /static/js/counter.js  None
WARNING:django.request:Not Found: /static/js/counter.js
30/Jan/2024 07:17:52   WARNING  Not Found: /static/images/o-mastere-na-chas.png  None
WARNING:django.request:Not Found: /static/images/o-mastere-na-chas.png
30/Jan/2024 07:17:53   WARNING  Not Found: /static/images/usluga-master-na-chas.jpg  None
WARNING:django.request:Not Found: /static/images/usluga-master-na-chas.jpg
30/Jan/2024 07:18:22   WARNING  Not Found: /static/images/whatsapp.png  None
WARNING:django.request:Not Found: /static/images/whatsapp.png
30/Jan/2024 07:18:22   WARNING  Not Found: /static/images/o-mastere-na-chas.png  None
WARNING:django.request:Not Found: /static/images/o-mastere-na-chas.png
30/Jan/2024 07:18:22   WARNING  Not Found: /static/js/counter.js  None
WARNING:django.request:Not Found: /static/js/counter.js
30/Jan/2024 07:18:35   ERROR  Invalid HTTP_HOST header: '127.0.0.1:8000'. You may need to add '127.0.0.1' to ALLOWED_HOSTS.  (<class 'django.core.exceptions.DisallowedHost'>, DisallowedHost("Invalid HTTP_HOST header: '127.0.0.1:8000'. You may need to add '127.0.0.1' to ALLOWED_HOSTS."), <traceback object at 0x7fd56c554780>)
Traceback (most recent call last):
  File "/home/alprostov/PycharmProjects/sakhlis/venv3/lib/python3.11/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/home/alprostov/PycharmProjects/sakhlis/venv3/lib/python3.11/site-packages/django/utils/deprecation.py", line 133, in __call__
    response = self.process_request(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/alprostov/PycharmProjects/sakhlis/venv3/lib/python3.11/site-packages/django/middleware/common.py", line 48, in process_request
    host = request.get_host()
           ^^^^^^^^^^^^^^^^^^
  File "/home/alprostov/PycharmProjects/sakhlis/venv3/lib/python3.11/site-packages/django/http/request.py", line 167, in get_host
    raise DisallowedHost(msg)
django.core.exceptions.DisallowedHost: Invalid HTTP_HOST header: '127.0.0.1:8000'. You may need to add '127.0.0.1' to ALLOWED_HOSTS.
30/Jan/2024 07:18:36   WARNING  Bad Request: /  None
WARNING:django.request:Bad Request: /
30/Jan/2024 07:18:36   ERROR  Invalid HTTP_HOST header: '127.0.0.1:8000'. You may need to add '127.0.0.1' to ALLOWED_HOSTS.  (<class 'django.core.exceptions.DisallowedHost'>, DisallowedHost("Invalid HTTP_HOST header: '127.0.0.1:8000'. You may need to add '127.0.0.1' to ALLOWED_HOSTS."), <traceback object at 0x7fd56c5e4880>)
Traceback (most recent call last):
  File "/home/alprostov/PycharmProjects/sakhlis/venv3/lib/python3.11/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/home/alprostov/PycharmProjects/sakhlis/venv3/lib/python3.11/site-packages/django/utils/deprecation.py", line 133, in __call__
    response = self.process_request(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/alprostov/PycharmProjects/sakhlis/venv3/lib/python3.11/site-packages/django/middleware/common.py", line 48, in process_request
    host = request.get_host()
           ^^^^^^^^^^^^^^^^^^
  File "/home/alprostov/PycharmProjects/sakhlis/venv3/lib/python3.11/site-packages/django/http/request.py", line 167, in get_host
    raise DisallowedHost(msg)
django.core.exceptions.DisallowedHost: Invalid HTTP_HOST header: '127.0.0.1:8000'. You may need to add '127.0.0.1' to ALLOWED_HOSTS.
ERROR:django.security.DisallowedHost:Invalid HTTP_HOST header: '127.0.0.1:8000'. You may need to add '127.0.0.1' to ALLOWED_HOSTS.
Traceback (most recent call last):
  File "/home/alprostov/PycharmProjects/sakhlis/venv3/lib/python3.11/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/home/alprostov/PycharmProjects/sakhlis/venv3/lib/python3.11/site-packages/django/utils/deprecation.py", line 133, in __call__
    response = self.process_request(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/alprostov/PycharmProjects/sakhlis/venv3/lib/python3.11/site-packages/django/middleware/common.py", line 48, in process_request
    host = request.get_host()
           ^^^^^^^^^^^^^^^^^^
  File "/home/alprostov/PycharmProjects/sakhlis/venv3/lib/python3.11/site-packages/django/http/request.py", line 167, in get_host
    raise DisallowedHost(msg)
django.core.exceptions.DisallowedHost: Invalid HTTP_HOST header: '127.0.0.1:8000'. You may need to add '127.0.0.1' to ALLOWED_HOSTS.
30/Jan/2024 07:18:36   WARNING  Bad Request: /  None
WARNING:django.request:Bad Request: /
30/Jan/2024 07:18:37   ERROR  Invalid HTTP_HOST header: '127.0.0.1:8000'. You may need to add '127.0.0.1' to ALLOWED_HOSTS.  (<class 'django.core.exceptions.DisallowedHost'>, DisallowedHost("Invalid HTTP_HOST header: '127.0.0.1:8000'. You may need to add '127.0.0.1' to ALLOWED_HOSTS."), <traceback object at 0x7fd56c5e66c0>)
Traceback (most recent call last):
  File "/home/alprostov/PycharmProjects/sakhlis/venv3/lib/python3.11/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/home/alprostov/PycharmProjects/sakhlis/venv3/lib/python3.11/site-packages/django/utils/deprecation.py", line 133, in __call__
    response = self.process_request(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/alprostov/PycharmProjects/sakhlis/venv3/lib/python3.11/site-packages/django/middleware/common.py", line 48, in process_request
    host = request.get_host()
           ^^^^^^^^^^^^^^^^^^
  File "/home/alprostov/PycharmProjects/sakhlis/venv3/lib/python3.11/site-packages/django/http/request.py", line 167, in get_host
    raise DisallowedHost(msg)
django.core.exceptions.DisallowedHost: Invalid HTTP_HOST header: '127.0.0.1:8000'. You may need to add '127.0.0.1' to ALLOWED_HOSTS.
ERROR:django.security.DisallowedHost:Invalid HTTP_HOST header: '127.0.0.1:8000'. You may need to add '127.0.0.1' to ALLOWED_HOSTS.
Traceback (most recent call last):
  File "/home/alprostov/PycharmProjects/sakhlis/venv3/lib/python3.11/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/home/alprostov/PycharmProjects/sakhlis/venv3/lib/python3.11/site-packages/django/utils/deprecation.py", line 133, in __call__
    response = self.process_request(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/alprostov/PycharmProjects/sakhlis/venv3/lib/python3.11/site-packages/django/middleware/common.py", line 48, in process_request
    host = request.get_host()
           ^^^^^^^^^^^^^^^^^^
  File "/home/alprostov/PycharmProjects/sakhlis/venv3/lib/python3.11/site-packages/django/http/request.py", line 167, in get_host
    raise DisallowedHost(msg)
django.core.exceptions.DisallowedHost: Invalid HTTP_HOST header: '127.0.0.1:8000'. You may need to add '127.0.0.1' to ALLOWED_HOSTS.
30/Jan/2024 07:18:37   WARNING  Bad Request: /  None
WARNING:django.request:Bad Request: /
30/Jan/2024 07:18:39   ERROR  Invalid HTTP_HOST header: '127.0.0.1:8000'. You may need to add '127.0.0.1' to ALLOWED_HOSTS.  (<class 'django.core.exceptions.DisallowedHost'>, DisallowedHost("Invalid HTTP_HOST header: '127.0.0.1:8000'. You may need to add '127.0.0.1' to ALLOWED_HOSTS."), <traceback object at 0x7fd56c5e8740>)
Traceback (most recent call last):
  File "/home/alprostov/PycharmProjects/sakhlis/venv3/lib/python3.11/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/home/alprostov/PycharmProjects/sakhlis/venv3/lib/python3.11/site-packages/django/utils/deprecation.py", line 133, in __call__
    response = self.process_request(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/alprostov/PycharmProjects/sakhlis/venv3/lib/python3.11/site-packages/django/middleware/common.py", line 48, in process_request
    host = request.get_host()
           ^^^^^^^^^^^^^^^^^^
  File "/home/alprostov/PycharmProjects/sakhlis/venv3/lib/python3.11/site-packages/django/http/request.py", line 167, in get_host
    raise DisallowedHost(msg)
django.core.exceptions.DisallowedHost: Invalid HTTP_HOST header: '127.0.0.1:8000'. You may need to add '127.0.0.1' to ALLOWED_HOSTS.
ERROR:django.security.DisallowedHost:Invalid HTTP_HOST header: '127.0.0.1:8000'. You may need to add '127.0.0.1' to ALLOWED_HOSTS.
Traceback (most recent call last):
  File "/home/alprostov/PycharmProjects/sakhlis/venv3/lib/python3.11/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/home/alprostov/PycharmProjects/sakhlis/venv3/lib/python3.11/site-packages/django/utils/deprecation.py", line 133, in __call__
    response = self.process_request(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/alprostov/PycharmProjects/sakhlis/venv3/lib/python3.11/site-packages/django/middleware/common.py", line 48, in process_request
    host = request.get_host()
           ^^^^^^^^^^^^^^^^^^
  File "/home/alprostov/PycharmProjects/sakhlis/venv3/lib/python3.11/site-packages/django/http/request.py", line 167, in get_host
    raise DisallowedHost(msg)
django.core.exceptions.DisallowedHost: Invalid HTTP_HOST header: '127.0.0.1:8000'. You may need to add '127.0.0.1' to ALLOWED_HOSTS.
30/Jan/2024 07:18:39   WARNING  Bad Request: /admin/  None
WARNING:django.request:Bad Request: /admin/
30/Jan/2024 07:18:40   ERROR  Invalid HTTP_HOST header: '127.0.0.1:8000'. You may need to add '127.0.0.1' to ALLOWED_HOSTS.  (<class 'django.core.exceptions.DisallowedHost'>, DisallowedHost("Invalid HTTP_HOST header: '127.0.0.1:8000'. You may need to add '127.0.0.1' to ALLOWED_HOSTS."), <traceback object at 0x7fd56c5e6540>)
Traceback (most recent call last):
  File "/home/alprostov/PycharmProjects/sakhlis/venv3/lib/python3.11/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/home/alprostov/PycharmProjects/sakhlis/venv3/lib/python3.11/site-packages/django/utils/deprecation.py", line 133, in __call__
    response = self.process_request(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/alprostov/PycharmProjects/sakhlis/venv3/lib/python3.11/site-packages/django/middleware/common.py", line 48, in process_request
    host = request.get_host()
           ^^^^^^^^^^^^^^^^^^
  File "/home/alprostov/PycharmProjects/sakhlis/venv3/lib/python3.11/site-packages/django/http/request.py", line 167, in get_host
    raise DisallowedHost(msg)
django.core.exceptions.DisallowedHost: Invalid HTTP_HOST header: '127.0.0.1:8000'. You may need to add '127.0.0.1' to ALLOWED_HOSTS.
ERROR:django.security.DisallowedHost:Invalid HTTP_HOST header: '127.0.0.1:8000'. You may need to add '127.0.0.1' to ALLOWED_HOSTS.
Traceback (most recent call last):
  File "/home/alprostov/PycharmProjects/sakhlis/venv3/lib/python3.11/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/home/alprostov/PycharmProjects/sakhlis/venv3/lib/python3.11/site-packages/django/utils/deprecation.py", line 133, in __call__
    response = self.process_request(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/alprostov/PycharmProjects/sakhlis/venv3/lib/python3.11/site-packages/django/middleware/common.py", line 48, in process_request
    host = request.get_host()
           ^^^^^^^^^^^^^^^^^^
  File "/home/alprostov/PycharmProjects/sakhlis/venv3/lib/python3.11/site-packages/django/http/request.py", line 167, in get_host
    raise DisallowedHost(msg)
django.core.exceptions.DisallowedHost: Invalid HTTP_HOST header: '127.0.0.1:8000'. You may need to add '127.0.0.1' to ALLOWED_HOSTS.
30/Jan/2024 07:18:40   WARNING  Bad Request: /admin/  None
WARNING:django.request:Bad Request: /admin/
30/Jan/2024 07:18:49   ERROR  Invalid HTTP_HOST header: '127.0.0.1:8000'. You may need to add '127.0.0.1' to ALLOWED_HOSTS.  (<class 'django.core.exceptions.DisallowedHost'>, DisallowedHost("Invalid HTTP_HOST header: '127.0.0.1:8000'. You may need to add '127.0.0.1' to ALLOWED_HOSTS."), <traceback object at 0x7fd56c5e42c0>)
Traceback (most recent call last):
  File "/home/alprostov/PycharmProjects/sakhlis/venv3/lib/python3.11/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/home/alprostov/PycharmProjects/sakhlis/venv3/lib/python3.11/site-packages/django/utils/deprecation.py", line 133, in __call__
    response = self.process_request(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/alprostov/PycharmProjects/sakhlis/venv3/lib/python3.11/site-packages/django/middleware/common.py", line 48, in process_request
    host = request.get_host()
           ^^^^^^^^^^^^^^^^^^
  File "/home/alprostov/PycharmProjects/sakhlis/venv3/lib/python3.11/site-packages/django/http/request.py", line 167, in get_host
    raise DisallowedHost(msg)
django.core.exceptions.DisallowedHost: Invalid HTTP_HOST header: '127.0.0.1:8000'. You may need to add '127.0.0.1' to ALLOWED_HOSTS.
ERROR:django.security.DisallowedHost:Invalid HTTP_HOST header: '127.0.0.1:8000'. You may need to add '127.0.0.1' to ALLOWED_HOSTS.
Traceback (most recent call last):
  File "/home/alprostov/PycharmProjects/sakhlis/venv3/lib/python3.11/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/home/alprostov/PycharmProjects/sakhlis/venv3/lib/python3.11/site-packages/django/utils/deprecation.py", line 133, in __call__
    response = self.process_request(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/alprostov/PycharmProjects/sakhlis/venv3/lib/python3.11/site-packages/django/middleware/common.py", line 48, in process_request
    host = request.get_host()
           ^^^^^^^^^^^^^^^^^^
  File "/home/alprostov/PycharmProjects/sakhlis/venv3/lib/python3.11/site-packages/django/http/request.py", line 167, in get_host
    raise DisallowedHost(msg)
django.core.exceptions.DisallowedHost: Invalid HTTP_HOST header: '127.0.0.1:8000'. You may need to add '127.0.0.1' to ALLOWED_HOSTS.
30/Jan/2024 07:18:49   WARNING  Bad Request: /admin/  None
WARNING:django.request:Bad Request: /admin/
30/Jan/2024 07:19:01   WARNING  Not Found: /static/images/whatsapp.png  None
WARNING:django.request:Not Found: /static/images/whatsapp.png
30/Jan/2024 07:19:01   WARNING  Not Found: /static/js/counter.js  None
WARNING:django.request:Not Found: /static/js/counter.js
30/Jan/2024 07:19:01   WARNING  Not Found: /static/images/o-mastere-na-chas.png  None
WARNING:django.request:Not Found: /static/images/o-mastere-na-chas.png
30/Jan/2024 07:19:01   WARNING  Not Found: /static/images/usluga-master-na-chas.jpg  None
WARNING:django.request:Not Found: /static/images/usluga-master-na-chas.jpg
30/Jan/2024 07:19:26   WARNING  Not Found: /static/js/counter.js  None
WARNING:django.request:Not Found: /static/js/counter.js
30/Jan/2024 07:47:11   WARNING  "GET /static/js/counter.js HTTP/1.1" 404 1798  None
WARNING:django.server:"GET /static/js/counter.js HTTP/1.1" 404 1798
30/Jan/2024 07:47:13   WARNING  "GET /static/js/counter.js HTTP/1.1" 404 1798  None
WARNING:django.server:"GET /static/js/counter.js HTTP/1.1" 404 1798
30/Jan/2024 07:54:04   ERROR  "GET / HTTP/1.1" 500 59  None
ERROR:django.server:"GET / HTTP/1.1" 500 59
30/Jan/2024 08:24:01   WARNING  "GET /static/js/counter.js HTTP/1.1" 404 1798  None
WARNING:django.server:"GET /static/js/counter.js HTTP/1.1" 404 1798
30/Jan/2024 08:24:29   ERROR  Invalid HTTP_HOST header: '127.0.0.1:8000'. You may need to add '127.0.0.1' to ALLOWED_HOSTS.  (<class 'django.core.exceptions.DisallowedHost'>, DisallowedHost("Invalid HTTP_HOST header: '127.0.0.1:8000'. You may need to add '127.0.0.1' to ALLOWED_HOSTS."), <traceback object at 0x7f6c82959600>)
Traceback (most recent call last):
  File "/home/alprostov/PycharmProjects/sakhlis/venv3/lib/python3.11/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/home/alprostov/PycharmProjects/sakhlis/venv3/lib/python3.11/site-packages/django/utils/deprecation.py", line 133, in __call__
    response = self.process_request(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/alprostov/PycharmProjects/sakhlis/venv3/lib/python3.11/site-packages/django/middleware/common.py", line 48, in process_request
    host = request.get_host()
           ^^^^^^^^^^^^^^^^^^
  File "/home/alprostov/PycharmProjects/sakhlis/venv3/lib/python3.11/site-packages/django/http/request.py", line 167, in get_host
    raise DisallowedHost(msg)
django.core.exceptions.DisallowedHost: Invalid HTTP_HOST header: '127.0.0.1:8000'. You may need to add '127.0.0.1' to ALLOWED_HOSTS.
30/Jan/2024 08:24:29   WARNING  Bad Request: /  None
WARNING:django.request:Bad Request: /
30/Jan/2024 08:25:05   ERROR  Invalid HTTP_HOST header: '127.0.0.1:8000'. You may need to add '127.0.0.1' to ALLOWED_HOSTS.  (<class 'django.core.exceptions.DisallowedHost'>, DisallowedHost("Invalid HTTP_HOST header: '127.0.0.1:8000'. You may need to add '127.0.0.1' to ALLOWED_HOSTS."), <traceback object at 0x7f6c82961180>)
Traceback (most recent call last):
  File "/home/alprostov/PycharmProjects/sakhlis/venv3/lib/python3.11/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/home/alprostov/PycharmProjects/sakhlis/venv3/lib/python3.11/site-packages/django/utils/deprecation.py", line 133, in __call__
    response = self.process_request(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/alprostov/PycharmProjects/sakhlis/venv3/lib/python3.11/site-packages/django/middleware/common.py", line 48, in process_request
    host = request.get_host()
           ^^^^^^^^^^^^^^^^^^
  File "/home/alprostov/PycharmProjects/sakhlis/venv3/lib/python3.11/site-packages/django/http/request.py", line 167, in get_host
    raise DisallowedHost(msg)
django.core.exceptions.DisallowedHost: Invalid HTTP_HOST header: '127.0.0.1:8000'. You may need to add '127.0.0.1' to ALLOWED_HOSTS.
30/Jan/2024 08:25:05   WARNING  Bad Request: /list_order  None
WARNING:django.request:Bad Request: /list_order
30/Jan/2024 08:26:13   WARNING  Not Found: /static/js/counter.js  None
WARNING:django.request:Not Found: /static/js/counter.js
30/Jan/2024 08:26:13   WARNING  "GET /static/js/counter.js HTTP/1.1" 404 4239  None
WARNING:django.server:"GET /static/js/counter.js HTTP/1.1" 404 4239
30/Jan/2024 08:27:50   WARNING  "GET /static/js/counter.js HTTP/1.1" 404 1798  None
WARNING:django.server:"GET /static/js/counter.js HTTP/1.1" 404 1798
30/Jan/2024 16:14:36   WARNING  "GET /static/js/counter.js HTTP/1.1" 404 1798  None
WARNING:django.server:"GET /static/js/counter.js HTTP/1.1" 404 1798
30/Jan/2024 16:14:39   WARNING  "GET /static/js/counter.js HTTP/1.1" 404 1798  None
WARNING:django.server:"GET /static/js/counter.js HTTP/1.1" 404 1798
30/Jan/2024 16:14:40   WARNING  "GET /static/js/counter.js HTTP/1.1" 404 1798  None
WARNING:django.server:"GET /static/js/counter.js HTTP/1.1" 404 1798
30/Jan/2024 16:14:47   WARNING  "GET /static/js/counter.js HTTP/1.1" 404 1798  None
WARNING:django.server:"GET /static/js/counter.js HTTP/1.1" 404 1798
30/Jan/2024 16:29:23   WARNING  "GET /static/js/counter.js HTTP/1.1" 404 1798  None
WARNING:django.server:"GET /static/js/counter.js HTTP/1.1" 404 1798
30/Jan/2024 16:29:46   WARNING  "GET /static/js/counter.js HTTP/1.1" 404 1798  None
WARNING:django.server:"GET /static/js/counter.js HTTP/1.1" 404 1798
30/Jan/2024 16:30:04   WARNING  "GET /static/js/counter.js HTTP/1.1" 404 1798  None
WARNING:django.server:"GET /static/js/counter.js HTTP/1.1" 404 1798
30/Jan/2024 16:30:12   WARNING  "GET /static/js/counter.js HTTP/1.1" 404 1798  None
WARNING:django.server:"GET /static/js/counter.js HTTP/1.1" 404 1798
30/Jan/2024 16:30:15   WARNING  "GET /static/js/counter.js HTTP/1.1" 404 1798  None
WARNING:django.server:"GET /static/js/counter.js HTTP/1.1" 404 1798
30/Jan/2024 16:38:22   WARNING  "GET /static/js/counter.js HTTP/1.1" 404 1798  None
WARNING:django.server:"GET /static/js/counter.js HTTP/1.1" 404 1798
30/Jan/2024 16:38:24   WARNING  "GET /static/js/counter.js HTTP/1.1" 404 1798  None
WARNING:django.server:"GET /static/js/counter.js HTTP/1.1" 404 1798
30/Jan/2024 16:38:30   WARNING  "GET /static/js/counter.js HTTP/1.1" 404 1798  None
WARNING:django.server:"GET /static/js/counter.js HTTP/1.1" 404 1798
