27/Nov/2024 08:56:51    ERROR    log    Internal Server Error: /list_order   /home/alprostov/PycharmProjects/sakhlis/web/venv/lib/python3.11/site-packages/django/utils/log.py   (<class 'TypeError'>, TypeError("'OrderFilter' object is not subscriptable"), <traceback object at 0x7f556b5d8940>)
Traceback (most recent call last):
  File "/home/alprostov/PycharmProjects/sakhlis/web/venv/lib/python3.11/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/home/alprostov/PycharmProjects/sakhlis/web/venv/lib/python3.11/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/alprostov/PycharmProjects/sakhlis/web/venv/lib/python3.11/site-packages/django/views/generic/base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/alprostov/PycharmProjects/sakhlis/web/venv/lib/python3.11/site-packages/django/contrib/auth/mixins.py", line 73, in dispatch
    return super().dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/alprostov/PycharmProjects/sakhlis/web/venv/lib/python3.11/site-packages/django/views/generic/base.py", line 143, in dispatch
    return handler(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/alprostov/PycharmProjects/sakhlis/web/venv/lib/python3.11/site-packages/django/views/generic/list.py", line 174, in get
    context = self.get_context_data()
              ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/alprostov/PycharmProjects/sakhlis/web/app_site/views.py", line 340, in get_context_data
    context['filterset'] = self.filterset[0:10]
                           ~~~~~~~~~~~~~~^^^^^^
TypeError: 'OrderFilter' object is not subscriptable
27/Nov/2024 08:56:51    ERROR    basehttp    "GET /list_order HTTP/1.1" 500 105971   /home/alprostov/PycharmProjects/sakhlis/web/venv/lib/python3.11/site-packages/django/core/servers/basehttp.py   None
27/Nov/2024 08:57:22    ERROR    log    Internal Server Error: /list_order   /home/alprostov/PycharmProjects/sakhlis/web/venv/lib/python3.11/site-packages/django/utils/log.py   (<class 'TypeError'>, TypeError("'OrderFilter' object is not subscriptable"), <traceback object at 0x7fbec0080700>)
Traceback (most recent call last):
  File "/home/alprostov/PycharmProjects/sakhlis/web/venv/lib/python3.11/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/home/alprostov/PycharmProjects/sakhlis/web/venv/lib/python3.11/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/alprostov/PycharmProjects/sakhlis/web/venv/lib/python3.11/site-packages/django/views/generic/base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/alprostov/PycharmProjects/sakhlis/web/venv/lib/python3.11/site-packages/django/contrib/auth/mixins.py", line 73, in dispatch
    return super().dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/alprostov/PycharmProjects/sakhlis/web/venv/lib/python3.11/site-packages/django/views/generic/base.py", line 143, in dispatch
    return handler(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/alprostov/PycharmProjects/sakhlis/web/venv/lib/python3.11/site-packages/django/views/generic/list.py", line 154, in get
    self.object_list = self.get_queryset()
                       ^^^^^^^^^^^^^^^^^^^
  File "/home/alprostov/PycharmProjects/sakhlis/web/app_site/views.py", line 335, in get_queryset
    self.filterset = OrderFilter(self.request.GET, queryset)[0:10]
                     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^
TypeError: 'OrderFilter' object is not subscriptable
27/Nov/2024 08:57:22    ERROR    basehttp    "GET /list_order HTTP/1.1" 500 106134   /home/alprostov/PycharmProjects/sakhlis/web/venv/lib/python3.11/site-packages/django/core/servers/basehttp.py   None
27/Nov/2024 08:57:23    ERROR    log    Internal Server Error: /list_order   /home/alprostov/PycharmProjects/sakhlis/web/venv/lib/python3.11/site-packages/django/utils/log.py   (<class 'TypeError'>, TypeError("'OrderFilter' object is not subscriptable"), <traceback object at 0x7fbec01d4980>)
Traceback (most recent call last):
  File "/home/alprostov/PycharmProjects/sakhlis/web/venv/lib/python3.11/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/home/alprostov/PycharmProjects/sakhlis/web/venv/lib/python3.11/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/alprostov/PycharmProjects/sakhlis/web/venv/lib/python3.11/site-packages/django/views/generic/base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/alprostov/PycharmProjects/sakhlis/web/venv/lib/python3.11/site-packages/django/contrib/auth/mixins.py", line 73, in dispatch
    return super().dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/alprostov/PycharmProjects/sakhlis/web/venv/lib/python3.11/site-packages/django/views/generic/base.py", line 143, in dispatch
    return handler(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/alprostov/PycharmProjects/sakhlis/web/venv/lib/python3.11/site-packages/django/views/generic/list.py", line 154, in get
    self.object_list = self.get_queryset()
                       ^^^^^^^^^^^^^^^^^^^
  File "/home/alprostov/PycharmProjects/sakhlis/web/app_site/views.py", line 335, in get_queryset
    self.filterset = OrderFilter(self.request.GET, queryset)[0:10]
                     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^
TypeError: 'OrderFilter' object is not subscriptable
27/Nov/2024 08:57:23    ERROR    basehttp    "GET /list_order HTTP/1.1" 500 106132   /home/alprostov/PycharmProjects/sakhlis/web/venv/lib/python3.11/site-packages/django/core/servers/basehttp.py   None
27/Nov/2024 08:57:46    WARNING    log    Not Found: /media/masters/unknown_person.jpg   /home/alprostov/PycharmProjects/sakhlis/web/venv/lib/python3.11/site-packages/django/utils/log.py   None
27/Nov/2024 08:57:46    WARNING    basehttp    "GET /media/masters/unknown_person.jpg HTTP/1.1" 404 19523   /home/alprostov/PycharmProjects/sakhlis/web/venv/lib/python3.11/site-packages/django/core/servers/basehttp.py   None
27/Nov/2024 08:59:44    WARNING    log    Not Found: /media/masters/unknown_person.jpg   /home/alprostov/PycharmProjects/sakhlis/web/venv/lib/python3.11/site-packages/django/utils/log.py   None
27/Nov/2024 08:59:44    WARNING    basehttp    "GET /media/masters/unknown_person.jpg HTTP/1.1" 404 19523   /home/alprostov/PycharmProjects/sakhlis/web/venv/lib/python3.11/site-packages/django/core/servers/basehttp.py   None
27/Nov/2024 08:59:45    WARNING    log    Not Found: /media/masters/unknown_person.jpg   /home/alprostov/PycharmProjects/sakhlis/web/venv/lib/python3.11/site-packages/django/utils/log.py   None
27/Nov/2024 08:59:45    WARNING    basehttp    "GET /media/masters/unknown_person.jpg HTTP/1.1" 404 19523   /home/alprostov/PycharmProjects/sakhlis/web/venv/lib/python3.11/site-packages/django/core/servers/basehttp.py   None
27/Nov/2024 09:13:11    WARNING    log    Not Found: /media/masters/unknown_person.jpg   /home/alprostov/PycharmProjects/sakhlis/web/venv/lib/python3.11/site-packages/django/utils/log.py   None
27/Nov/2024 09:13:11    WARNING    basehttp    "GET /media/masters/unknown_person.jpg HTTP/1.1" 404 19523   /home/alprostov/PycharmProjects/sakhlis/web/venv/lib/python3.11/site-packages/django/core/servers/basehttp.py   None
27/Nov/2024 09:13:18    WARNING    log    Not Found: /media/masters/unknown_person.jpg   /home/alprostov/PycharmProjects/sakhlis/web/venv/lib/python3.11/site-packages/django/utils/log.py   None
27/Nov/2024 09:13:18    WARNING    basehttp    "GET /media/masters/unknown_person.jpg HTTP/1.1" 404 19523   /home/alprostov/PycharmProjects/sakhlis/web/venv/lib/python3.11/site-packages/django/core/servers/basehttp.py   None
27/Nov/2024 09:13:19    WARNING    log    Not Found: /media/masters/unknown_person.jpg   /home/alprostov/PycharmProjects/sakhlis/web/venv/lib/python3.11/site-packages/django/utils/log.py   None
27/Nov/2024 09:13:19    WARNING    basehttp    "GET /media/masters/unknown_person.jpg HTTP/1.1" 404 19523   /home/alprostov/PycharmProjects/sakhlis/web/venv/lib/python3.11/site-packages/django/core/servers/basehttp.py   None
27/Nov/2024 09:13:20    WARNING    log    Not Found: /media/masters/unknown_person.jpg   /home/alprostov/PycharmProjects/sakhlis/web/venv/lib/python3.11/site-packages/django/utils/log.py   None
27/Nov/2024 09:13:20    WARNING    basehttp    "GET /media/masters/unknown_person.jpg HTTP/1.1" 404 19523   /home/alprostov/PycharmProjects/sakhlis/web/venv/lib/python3.11/site-packages/django/core/servers/basehttp.py   None
27/Nov/2024 09:13:20    WARNING    log    Not Found: /media/masters/unknown_person.jpg   /home/alprostov/PycharmProjects/sakhlis/web/venv/lib/python3.11/site-packages/django/utils/log.py   None
27/Nov/2024 09:13:20    WARNING    basehttp    "GET /media/masters/unknown_person.jpg HTTP/1.1" 404 19523   /home/alprostov/PycharmProjects/sakhlis/web/venv/lib/python3.11/site-packages/django/core/servers/basehttp.py   None
27/Nov/2024 09:13:20    WARNING    log    Not Found: /media/masters/unknown_person.jpg   /home/alprostov/PycharmProjects/sakhlis/web/venv/lib/python3.11/site-packages/django/utils/log.py   None
27/Nov/2024 09:13:20    WARNING    basehttp    "GET /media/masters/unknown_person.jpg HTTP/1.1" 404 19523   /home/alprostov/PycharmProjects/sakhlis/web/venv/lib/python3.11/site-packages/django/core/servers/basehttp.py   None
27/Nov/2024 09:13:37    WARNING    log    Not Found: /media/masters/unknown_person.jpg   /home/alprostov/PycharmProjects/sakhlis/web/venv/lib/python3.11/site-packages/django/utils/log.py   None
27/Nov/2024 09:13:37    WARNING    basehttp    "GET /media/masters/unknown_person.jpg HTTP/1.1" 404 19523   /home/alprostov/PycharmProjects/sakhlis/web/venv/lib/python3.11/site-packages/django/core/servers/basehttp.py   None
27/Nov/2024 09:31:47    WARNING    log    Not Found: /favicon.ico   /home/alprostov/PycharmProjects/sakhlis/web/venv/lib/python3.11/site-packages/django/utils/log.py   None
27/Nov/2024 09:31:47    WARNING    basehttp    "GET /favicon.ico HTTP/1.1" 404 19223   /home/alprostov/PycharmProjects/sakhlis/web/venv/lib/python3.11/site-packages/django/core/servers/basehttp.py   None
27/Nov/2024 12:19:44    WARNING    log    Not Found: /favicon.ico   /home/alprostov/PycharmProjects/sakhlis/web/venv/lib/python3.11/site-packages/django/utils/log.py   None
27/Nov/2024 12:19:44    WARNING    basehttp    "GET /favicon.ico HTTP/1.1" 404 19223   /home/alprostov/PycharmProjects/sakhlis/web/venv/lib/python3.11/site-packages/django/core/servers/basehttp.py   None
27/Nov/2024 12:20:16    WARNING    log    Not Found: /media/masters/unknown_person.jpg   /home/alprostov/PycharmProjects/sakhlis/web/venv/lib/python3.11/site-packages/django/utils/log.py   None
27/Nov/2024 12:20:16    WARNING    basehttp    "GET /media/masters/unknown_person.jpg HTTP/1.1" 404 19523   /home/alprostov/PycharmProjects/sakhlis/web/venv/lib/python3.11/site-packages/django/core/servers/basehttp.py   None
27/Nov/2024 12:20:23    WARNING    log    Not Found: /media/masters/unknown_person.jpg   /home/alprostov/PycharmProjects/sakhlis/web/venv/lib/python3.11/site-packages/django/utils/log.py   None
27/Nov/2024 12:20:23    WARNING    basehttp    "GET /media/masters/unknown_person.jpg HTTP/1.1" 404 19523   /home/alprostov/PycharmProjects/sakhlis/web/venv/lib/python3.11/site-packages/django/core/servers/basehttp.py   None
27/Nov/2024 12:20:44    WARNING    log    Not Found: /media/masters/unknown_person.jpg   /home/alprostov/PycharmProjects/sakhlis/web/venv/lib/python3.11/site-packages/django/utils/log.py   None
27/Nov/2024 12:20:44    WARNING    basehttp    "GET /media/masters/unknown_person.jpg HTTP/1.1" 404 19523   /home/alprostov/PycharmProjects/sakhlis/web/venv/lib/python3.11/site-packages/django/core/servers/basehttp.py   None
27/Nov/2024 16:25:30    WARNING    log    Not Found: /favicon.ico   /home/alprostov/PycharmProjects/sakhlis/web/venv/lib/python3.11/site-packages/django/utils/log.py   None
27/Nov/2024 16:25:30    WARNING    basehttp    "GET /favicon.ico HTTP/1.1" 404 19223   /home/alprostov/PycharmProjects/sakhlis/web/venv/lib/python3.11/site-packages/django/core/servers/basehttp.py   None
27/Nov/2024 16:25:38    WARNING    log    Not Found: /media/images/appartment/photo_2024-09-16_21-41-10.jpg   /home/alprostov/PycharmProjects/sakhlis/web/venv/lib/python3.11/site-packages/django/utils/log.py   None
27/Nov/2024 16:25:38    WARNING    basehttp    "GET /media/images/appartment/photo_2024-09-16_21-41-10.jpg HTTP/1.1" 404 19630   /home/alprostov/PycharmProjects/sakhlis/web/venv/lib/python3.11/site-packages/django/core/servers/basehttp.py   None
27/Nov/2024 16:25:38    WARNING    log    Not Found: /media/images/appartment/photo_2024-09-12_22-00-08.jpg   /home/alprostov/PycharmProjects/sakhlis/web/venv/lib/python3.11/site-packages/django/utils/log.py   None
27/Nov/2024 16:25:38    WARNING    log    Not Found: /media/images/appartment/photo_2024-09-20_17-39-16.jpg   /home/alprostov/PycharmProjects/sakhlis/web/venv/lib/python3.11/site-packages/django/utils/log.py   None
27/Nov/2024 16:25:38    WARNING    basehttp    "GET /media/images/appartment/photo_2024-09-12_22-00-08.jpg HTTP/1.1" 404 19630   /home/alprostov/PycharmProjects/sakhlis/web/venv/lib/python3.11/site-packages/django/core/servers/basehttp.py   None
27/Nov/2024 16:25:38    WARNING    basehttp    "GET /media/images/appartment/photo_2024-09-20_17-39-16.jpg HTTP/1.1" 404 19630   /home/alprostov/PycharmProjects/sakhlis/web/venv/lib/python3.11/site-packages/django/core/servers/basehttp.py   None
27/Nov/2024 16:25:39    WARNING    log    Not Found: /media/images/appartment/photo_2024-09-12_21-08-19.jpg   /home/alprostov/PycharmProjects/sakhlis/web/venv/lib/python3.11/site-packages/django/utils/log.py   None
27/Nov/2024 16:25:39    WARNING    basehttp    "GET /media/images/appartment/photo_2024-09-12_21-08-19.jpg HTTP/1.1" 404 19630   /home/alprostov/PycharmProjects/sakhlis/web/venv/lib/python3.11/site-packages/django/core/servers/basehttp.py   None
27/Nov/2024 16:25:39    WARNING    log    Not Found: /media/images/appartment/photo_2024-09-22_12-15-37.jpg   /home/alprostov/PycharmProjects/sakhlis/web/venv/lib/python3.11/site-packages/django/utils/log.py   None
27/Nov/2024 16:25:39    WARNING    basehttp    "GET /media/images/appartment/photo_2024-09-22_12-15-37.jpg HTTP/1.1" 404 19630   /home/alprostov/PycharmProjects/sakhlis/web/venv/lib/python3.11/site-packages/django/core/servers/basehttp.py   None
27/Nov/2024 16:25:39    WARNING    log    Not Found: /media/images/appartment/photo_2024-09-12_20-59-28.jpg   /home/alprostov/PycharmProjects/sakhlis/web/venv/lib/python3.11/site-packages/django/utils/log.py   None
27/Nov/2024 16:25:39    WARNING    basehttp    "GET /media/images/appartment/photo_2024-09-12_20-59-28.jpg HTTP/1.1" 404 19630   /home/alprostov/PycharmProjects/sakhlis/web/venv/lib/python3.11/site-packages/django/core/servers/basehttp.py   None
27/Nov/2024 16:25:39    WARNING    log    Not Found: /media/images/appartment/photo_2024-09-16_21-23-19.jpg   /home/alprostov/PycharmProjects/sakhlis/web/venv/lib/python3.11/site-packages/django/utils/log.py   None
27/Nov/2024 16:25:39    WARNING    basehttp    "GET /media/images/appartment/photo_2024-09-16_21-23-19.jpg HTTP/1.1" 404 19630   /home/alprostov/PycharmProjects/sakhlis/web/venv/lib/python3.11/site-packages/django/core/servers/basehttp.py   None
27/Nov/2024 16:25:39    WARNING    log    Not Found: /media/images/appartment/photo_2024-09-20_16-37-55.jpg   /home/alprostov/PycharmProjects/sakhlis/web/venv/lib/python3.11/site-packages/django/utils/log.py   None
27/Nov/2024 16:25:39    WARNING    basehttp    "GET /media/images/appartment/photo_2024-09-20_16-37-55.jpg HTTP/1.1" 404 19630   /home/alprostov/PycharmProjects/sakhlis/web/venv/lib/python3.11/site-packages/django/core/servers/basehttp.py   None
27/Nov/2024 16:25:39    WARNING    log    Not Found: /media/images/appartment/photo_2024-09-13_20-52-44.jpg   /home/alprostov/PycharmProjects/sakhlis/web/venv/lib/python3.11/site-packages/django/utils/log.py   None
27/Nov/2024 16:25:39    WARNING    basehttp    "GET /media/images/appartment/photo_2024-09-13_20-52-44.jpg HTTP/1.1" 404 19630   /home/alprostov/PycharmProjects/sakhlis/web/venv/lib/python3.11/site-packages/django/core/servers/basehttp.py   None
27/Nov/2024 16:25:39    WARNING    log    Not Found: /media/images/appartment/236.jpg   /home/alprostov/PycharmProjects/sakhlis/web/venv/lib/python3.11/site-packages/django/utils/log.py   None
27/Nov/2024 16:25:39    WARNING    basehttp    "GET /media/images/appartment/236.jpg HTTP/1.1" 404 19520   /home/alprostov/PycharmProjects/sakhlis/web/venv/lib/python3.11/site-packages/django/core/servers/basehttp.py   None
27/Nov/2024 16:25:39    WARNING    log    Not Found: /media/images/appartment/photo_2024-09-16_21-48-59.jpg   /home/alprostov/PycharmProjects/sakhlis/web/venv/lib/python3.11/site-packages/django/utils/log.py   None
27/Nov/2024 16:25:39    WARNING    basehttp    "GET /media/images/appartment/photo_2024-09-16_21-48-59.jpg HTTP/1.1" 404 19630   /home/alprostov/PycharmProjects/sakhlis/web/venv/lib/python3.11/site-packages/django/core/servers/basehttp.py   None
27/Nov/2024 16:25:39    WARNING    log    Not Found: /media/images/appartment/photo_2024-09-13_20-50-02.jpg   /home/alprostov/PycharmProjects/sakhlis/web/venv/lib/python3.11/site-packages/django/utils/log.py   None
27/Nov/2024 16:25:39    WARNING    basehttp    "GET /media/images/appartment/photo_2024-09-13_20-50-02.jpg HTTP/1.1" 404 19630   /home/alprostov/PycharmProjects/sakhlis/web/venv/lib/python3.11/site-packages/django/core/servers/basehttp.py   None
27/Nov/2024 16:25:39    WARNING    log    Not Found: /media/images/appartment/2679.jpg   /home/alprostov/PycharmProjects/sakhlis/web/venv/lib/python3.11/site-packages/django/utils/log.py   None
27/Nov/2024 16:25:39    WARNING    basehttp    "GET /media/images/appartment/2679.jpg HTTP/1.1" 404 19525   /home/alprostov/PycharmProjects/sakhlis/web/venv/lib/python3.11/site-packages/django/core/servers/basehttp.py   None
27/Nov/2024 16:25:39    WARNING    log    Not Found: /media/images/appartment/2718.jpg   /home/alprostov/PycharmProjects/sakhlis/web/venv/lib/python3.11/site-packages/django/utils/log.py   None
27/Nov/2024 16:25:39    WARNING    basehttp    "GET /media/images/appartment/2718.jpg HTTP/1.1" 404 19525   /home/alprostov/PycharmProjects/sakhlis/web/venv/lib/python3.11/site-packages/django/core/servers/basehttp.py   None
27/Nov/2024 16:25:39    WARNING    log    Not Found: /media/images/appartment/photo_2024-09-12_21-08-19_jbnLNP4.jpg   /home/alprostov/PycharmProjects/sakhlis/web/venv/lib/python3.11/site-packages/django/utils/log.py   None
27/Nov/2024 16:25:39    WARNING    basehttp    "GET /media/images/appartment/photo_2024-09-12_21-08-19_jbnLNP4.jpg HTTP/1.1" 404 19670   /home/alprostov/PycharmProjects/sakhlis/web/venv/lib/python3.11/site-packages/django/core/servers/basehttp.py   None
27/Nov/2024 16:32:03    WARNING    log    Not Found: /media/images/appartment/photo_2024-09-12_22-00-08.jpg   /home/alprostov/PycharmProjects/sakhlis/web/venv/lib/python3.11/site-packages/django/utils/log.py   None
27/Nov/2024 16:32:03    WARNING    basehttp    "GET /media/images/appartment/photo_2024-09-12_22-00-08.jpg HTTP/1.1" 404 19630   /home/alprostov/PycharmProjects/sakhlis/web/venv/lib/python3.11/site-packages/django/core/servers/basehttp.py   None
27/Nov/2024 16:32:03    WARNING    log    Not Found: /media/images/appartment/photo_2024-09-16_21-41-10.jpg   /home/alprostov/PycharmProjects/sakhlis/web/venv/lib/python3.11/site-packages/django/utils/log.py   None
27/Nov/2024 16:32:03    WARNING    log    Not Found: /media/images/appartment/photo_2024-09-12_21-08-19.jpg   /home/alprostov/PycharmProjects/sakhlis/web/venv/lib/python3.11/site-packages/django/utils/log.py   None
27/Nov/2024 16:32:03    WARNING    basehttp    "GET /media/images/appartment/photo_2024-09-16_21-41-10.jpg HTTP/1.1" 404 19630   /home/alprostov/PycharmProjects/sakhlis/web/venv/lib/python3.11/site-packages/django/core/servers/basehttp.py   None
27/Nov/2024 16:32:03    WARNING    basehttp    "GET /media/images/appartment/photo_2024-09-12_21-08-19.jpg HTTP/1.1" 404 19630   /home/alprostov/PycharmProjects/sakhlis/web/venv/lib/python3.11/site-packages/django/core/servers/basehttp.py   None
27/Nov/2024 16:32:03    WARNING    log    Not Found: /media/images/appartment/photo_2024-09-20_17-39-16.jpg   /home/alprostov/PycharmProjects/sakhlis/web/venv/lib/python3.11/site-packages/django/utils/log.py   None
27/Nov/2024 16:32:03    WARNING    basehttp    "GET /media/images/appartment/photo_2024-09-20_17-39-16.jpg HTTP/1.1" 404 19630   /home/alprostov/PycharmProjects/sakhlis/web/venv/lib/python3.11/site-packages/django/core/servers/basehttp.py   None
27/Nov/2024 16:32:03    WARNING    log    Not Found: /media/images/appartment/photo_2024-09-12_20-59-28.jpg   /home/alprostov/PycharmProjects/sakhlis/web/venv/lib/python3.11/site-packages/django/utils/log.py   None
27/Nov/2024 16:32:03    WARNING    basehttp    "GET /media/images/appartment/photo_2024-09-12_20-59-28.jpg HTTP/1.1" 404 19630   /home/alprostov/PycharmProjects/sakhlis/web/venv/lib/python3.11/site-packages/django/core/servers/basehttp.py   None
27/Nov/2024 16:32:03    WARNING    log    Not Found: /media/images/appartment/photo_2024-09-22_12-15-37.jpg   /home/alprostov/PycharmProjects/sakhlis/web/venv/lib/python3.11/site-packages/django/utils/log.py   None
27/Nov/2024 16:32:03    WARNING    basehttp    "GET /media/images/appartment/photo_2024-09-22_12-15-37.jpg HTTP/1.1" 404 19630   /home/alprostov/PycharmProjects/sakhlis/web/venv/lib/python3.11/site-packages/django/core/servers/basehttp.py   None
27/Nov/2024 16:32:03    WARNING    log    Not Found: /media/images/appartment/photo_2024-09-13_20-52-44.jpg   /home/alprostov/PycharmProjects/sakhlis/web/venv/lib/python3.11/site-packages/django/utils/log.py   None
27/Nov/2024 16:32:03    WARNING    basehttp    "GET /media/images/appartment/photo_2024-09-13_20-52-44.jpg HTTP/1.1" 404 19630   /home/alprostov/PycharmProjects/sakhlis/web/venv/lib/python3.11/site-packages/django/core/servers/basehttp.py   None
27/Nov/2024 16:32:03    WARNING    log    Not Found: /media/images/appartment/photo_2024-09-16_21-23-19.jpg   /home/alprostov/PycharmProjects/sakhlis/web/venv/lib/python3.11/site-packages/django/utils/log.py   None
27/Nov/2024 16:32:03    WARNING    basehttp    "GET /media/images/appartment/photo_2024-09-16_21-23-19.jpg HTTP/1.1" 404 19630   /home/alprostov/PycharmProjects/sakhlis/web/venv/lib/python3.11/site-packages/django/core/servers/basehttp.py   None
27/Nov/2024 16:32:03    WARNING    log    Not Found: /media/images/appartment/236.jpg   /home/alprostov/PycharmProjects/sakhlis/web/venv/lib/python3.11/site-packages/django/utils/log.py   None
27/Nov/2024 16:32:03    WARNING    log    Not Found: /media/images/appartment/photo_2024-09-16_21-48-59.jpg   /home/alprostov/PycharmProjects/sakhlis/web/venv/lib/python3.11/site-packages/django/utils/log.py   None
27/Nov/2024 16:32:03    WARNING    basehttp    "GET /media/images/appartment/236.jpg HTTP/1.1" 404 19520   /home/alprostov/PycharmProjects/sakhlis/web/venv/lib/python3.11/site-packages/django/core/servers/basehttp.py   None
27/Nov/2024 16:32:03    WARNING    basehttp    "GET /media/images/appartment/photo_2024-09-16_21-48-59.jpg HTTP/1.1" 404 19630   /home/alprostov/PycharmProjects/sakhlis/web/venv/lib/python3.11/site-packages/django/core/servers/basehttp.py   None
27/Nov/2024 16:32:03    WARNING    log    Not Found: /media/images/appartment/photo_2024-09-20_16-37-55.jpg   /home/alprostov/PycharmProjects/sakhlis/web/venv/lib/python3.11/site-packages/django/utils/log.py   None
27/Nov/2024 16:32:03    WARNING    basehttp    "GET /media/images/appartment/photo_2024-09-20_16-37-55.jpg HTTP/1.1" 404 19630   /home/alprostov/PycharmProjects/sakhlis/web/venv/lib/python3.11/site-packages/django/core/servers/basehttp.py   None
27/Nov/2024 16:32:03    WARNING    log    Not Found: /media/images/appartment/photo_2024-09-13_20-50-02.jpg   /home/alprostov/PycharmProjects/sakhlis/web/venv/lib/python3.11/site-packages/django/utils/log.py   None
27/Nov/2024 16:32:03    WARNING    basehttp    "GET /media/images/appartment/photo_2024-09-13_20-50-02.jpg HTTP/1.1" 404 19630   /home/alprostov/PycharmProjects/sakhlis/web/venv/lib/python3.11/site-packages/django/core/servers/basehttp.py   None
27/Nov/2024 16:32:03    WARNING    log    Not Found: /media/images/appartment/2718.jpg   /home/alprostov/PycharmProjects/sakhlis/web/venv/lib/python3.11/site-packages/django/utils/log.py   None
27/Nov/2024 16:32:03    WARNING    basehttp    "GET /media/images/appartment/2718.jpg HTTP/1.1" 404 19525   /home/alprostov/PycharmProjects/sakhlis/web/venv/lib/python3.11/site-packages/django/core/servers/basehttp.py   None
27/Nov/2024 16:32:03    WARNING    log    Not Found: /media/images/appartment/2679.jpg   /home/alprostov/PycharmProjects/sakhlis/web/venv/lib/python3.11/site-packages/django/utils/log.py   None
27/Nov/2024 16:32:03    WARNING    basehttp    "GET /media/images/appartment/2679.jpg HTTP/1.1" 404 19525   /home/alprostov/PycharmProjects/sakhlis/web/venv/lib/python3.11/site-packages/django/core/servers/basehttp.py   None
27/Nov/2024 16:32:03    WARNING    log    Not Found: /media/images/appartment/photo_2024-09-12_21-08-19_jbnLNP4.jpg   /home/alprostov/PycharmProjects/sakhlis/web/venv/lib/python3.11/site-packages/django/utils/log.py   None
27/Nov/2024 16:32:03    WARNING    basehttp    "GET /media/images/appartment/photo_2024-09-12_21-08-19_jbnLNP4.jpg HTTP/1.1" 404 19670   /home/alprostov/PycharmProjects/sakhlis/web/venv/lib/python3.11/site-packages/django/core/servers/basehttp.py   None
28/Nov/2024 17:31:44    WARNING    log    Not Found: /favicon.ico   /home/alprostov/PycharmProjects/sakhlis/web/venv/lib/python3.11/site-packages/django/utils/log.py   None
28/Nov/2024 17:31:44    WARNING    basehttp    "GET /favicon.ico HTTP/1.1" 404 19223   /home/alprostov/PycharmProjects/sakhlis/web/venv/lib/python3.11/site-packages/django/core/servers/basehttp.py   None
28/Nov/2024 17:41:34    WARNING    basehttp    "GET /static/js/bootstrap.min.js.map HTTP/1.1" 404 1828   /home/alprostov/PycharmProjects/sakhlis/web/venv/lib/python3.11/site-packages/django/core/servers/basehttp.py   None
28/Nov/2024 17:41:34    WARNING    basehttp    "GET /static/css/bootstrap.min.css.map HTTP/1.1" 404 1834   /home/alprostov/PycharmProjects/sakhlis/web/venv/lib/python3.11/site-packages/django/core/servers/basehttp.py   None
